\section*{CLINICAL CHEMISTRY 1 CAT}
1. List the processes involved in urine formation
2. Describe the various types of urine deposits
3. Explain the cause of glycosuria in normoglycaemic state
4. Rothera's test turns negative while gerhardts is positive. Explain
5. Explain the role of the kidney in regulating fluid balance
6. Outline the renin-angiotensin-aldosterone system 5mks each

\section*{Long answer question}
1. Discuss the steps followed in performing standard urinalysis 20 mks
