\section*{ENTREPRENEURSHIP LAB MID SEMESTER CAT NOV 2022}

A viable business idea is one that
a) Has been tried and tested by many businessmen before
b) A unique opportunity that avails itself as a window of opportunity
c) Requires no need for external funding
d) That does not have risks involved

A good business opportunity may have three of the following characteristics except it should be?
a) attractive
b) durable
c) Lucrative
d) Timely

One of the following statements best explains the personal characteristics of entrepreneurs?
a) They are innovative, creative, and averse to risks
b) They are product/market oriented and always have capital to start the business
c) They are business-oriented persons who take calculated risks before they invest
d) They Creative innovators who are able to duplicate what is currently in the market

Which of the following is not included in the 4Ps of marketing?
a) Person
b) Product
c) Price
d) Promotion

Several forces are usually at play in a market and may determine an industry profitability. Identify one which is not a major force?
a) Threat of substitutes,
b) The entry of new competitors
c) The bargaining power of suppliers,
d) Bargaining power of the vendors

\section*{SHORT ANSWER QUESTION}

Define a target market? (2 MARKS)
Distinguish between and entrepreneur and entrepreneurship ( 2 MARKS)
With an example identify two kinds of entrepreneurs) 4 MARKS)
List two (2) reasons on what motivates people to become entrepreneurs (2 MARKS)

\section*{SECTION C -LONG ANSWER QUESTION (15 MARKS)}

You have identified a promising business venture. Preliminary market study review's that you may require more capital than you had anticipated. An idea clicks to you that you can do a good business plan which can attract external partners and financiers to enable you achieve your dream. Discuss in detail the fifteen (15) sections of a well-done business plan.
$* * * * * * * * * * * * * * * * * * * * * * * * * * *$
END $* * * * * * * * * * * * * * * * * * * * * * * * * * * * *$
