Processing PDF: /home/ngobiro/projects/pngobiro.github.io/colleges/tvet/certificate/Craft Certificate in Information Technology/Computer Application I (Theory)/pastpapers/knec/2015j(1).pdf
Starting PDF processing...
PDF processing started. ID: 2025_04_03_23f2c7fb29e0c150078dg
Polling PDF status (ID: 2025_04_03_23f2c7fb29e0c150078dg)...
Attempt 1: Status = completed, Progress = 100.0%
PDF processing completed successfully.
Fetching MMD result (ID: 2025_04_03_23f2c7fb29e0c150078dg)...

--- Converted MMD Start ---
Name $\qquad$ Index No. $\qquad$ 1 $\qquad$

1920/102A
COMPUTER APPLICATIONS I (THEORY)
Paper 1
July 2015
Time: 1 hour
![](https://cdn.mathpix.com/cropped/2025_04_03_23f2c7fb29e0c150078dg-1.jpg?height=284&width=258&top_left_y=573&top_left_x=1006)

THE KENYA NATIONAL EXAMINATIONS COUNCIL

\section*{CRAFT CERTIFICATE IN INFORMATION STUDIES}
![](https://cdn.mathpix.com/cropped/2025_04_03_23f2c7fb29e0c150078dg-1.jpg?height=398&width=1106&top_left_y=1105&top_left_x=685)

\section*{INSTRUCTIONS TO CANDIDATES}

Write your name and index number in the spaces provided above.
Sign and write the date of examination in the spaces provided above. Answer All the questions in this paper in the spaces provided.
Candidates should answer the questions in English.
For Examiner's Use Only
\begin{tabular}{|c|c|c|c|c|c|c|c|c|c|c|c|}
\hline Question & 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 & \begin{tabular}{c} 
Total \\
Score
\end{tabular} \\
\hline \begin{tabular}{c} 
Candidate's \\
Score
\end{tabular} & & & & & & & & & & \\
\hline
\end{tabular}

This paper consists of 5 printed pages.
Candidates should check the question paper to ascertain that all the pages are printed as indicated and that no questions are missing.
1. (a) Explain two advantages of the graphical user interface in computers.
$\qquad$
$\qquad$
$\qquad$
$\qquad$
(b) Jane came across the following types of software when revising for examination; Antivirus, Linux, backup software and Android
Classify them as either utility or operating system software.
$\qquad$
$\qquad$
$\qquad$
2. (a) Outline the function of each of the following keyboand dey SiRR $A$ R:
(i) F 10 ;
![](https://cdn.mathpix.com/cropped/2025_04_03_23f2c7fb29e0c150078dg-2.jpg?height=238&width=744&top_left_y=1311&top_left_x=1232)
(ii) Escape.
(b) Explain the term conditional formatting as used in spreadsheet applications.
$\qquad$
$\qquad$
$\qquad$
3. Distinguish between auto complete and auto correct as used in word processing applications.
$\qquad$
$\qquad$
$\qquad$
$\qquad$
4. With the aid of an example in each case, explain the following types of cell references as used in spreadsheet programs:
(i) absolute;
$\qquad$
$\qquad$
$\qquad$
$\qquad$
(ii) relative.
![](https://cdn.mathpix.com/cropped/2025_04_03_23f2c7fb29e0c150078dg-3.jpg?height=353&width=1685&top_left_y=933&top_left_x=324)
(b) Figure 1 shows an extract of a wotksheet. Use it to answer the question that follows.
\begin{tabular}{|c|c|l|l|}
\hline & \multicolumn{1}{|c|}{ A } & \multicolumn{1}{|c|}{ B } & C \\
\hline 1 & DAY & FRUIT & \\
\hline 2 & 1 & Mango & \\
\hline 3 & 2 & Passion & \\
\hline 4 & 3 & Mellon & \\
\hline 5 & 4 & Mellon & \\
\hline 6 & 5 & Passion & \\
\hline 7 & 6 & Mellon & \\
\hline 8 & & & \\
\hline
\end{tabular}

Figure 1
Write a formula in cell B8 that could be used to count Mellon occurrences.
$\qquad$
$\qquad$
$\qquad$
$\qquad$
6. Zippy set the following field properties in a database table:
(i) input mask;
(ii) indexed.

Explain the function of each property.
$\qquad$
$\qquad$
$\qquad$
$\qquad$
7. With the aid of a diagram, describe each of the following types of relationships as applied in
database applications:
(i) one-to-many;
![](https://cdn.mathpix.com/cropped/2025_04_03_23f2c7fb29e0c150078dg-4.jpg?height=410&width=1680&top_left_y=1093&top_left_x=258)
(ii) many-to-many.
$\qquad$
$\qquad$
$\qquad$
$\qquad$
$\qquad$
$\qquad$
8. Kirundi secondary school intends to introduce the use of the Internet to its students. Explain two negative social security issues that the students are likely to be exposed to.
$\qquad$
$\qquad$
$\qquad$
$\qquad$
$\qquad$
9. (a) Moses intends to print a 20 slide presentation and produce four slides per page. Explain the feature that he could use to achieve this objective.
$\qquad$
$\qquad$
$\qquad$
(b) Wireless fidelity (Wi-Fi) has become one of the most popular modes of Internet connection in recent days. Explain two reasons for this trend.
![](https://cdn.mathpix.com/cropped/2025_04_03_23f2c7fb29e0c150078dg-5.jpg?height=384&width=1679&top_left_y=846&top_left_x=247)
$\qquad$
$\qquad$
$\qquad$
10. (a) Explain the function of format painter feature as applied in computer applications.
$\qquad$
$\qquad$
$\qquad$
$\qquad$
(b) Explain the circumstance under which hide slide feature would be used in a presentation.
$\qquad$
$\qquad$
$\qquad$
$\qquad$
--- Converted MMD End ---
