Processing PDF: /home/ngobiro/projects/pngobiro.github.io/colleges/tvet/certificate/Craft Certificate in Information Technology/Computer Application I (Theory)/pastpapers/knec/2017july.pdf
Starting PDF processing...
PDF processing started. ID: 2025_04_03_02e52bef732d075c170ag
Polling PDF status (ID: 2025_04_03_02e52bef732d075c170ag)...
Attempt 1: Status = completed, Progress = 100.0%
PDF processing completed successfully.
Fetching MMD result (ID: 2025_04_03_02e52bef732d075c170ag)...

--- Converted MMD Start ---
\section*{THE KENYA NATIONAL EXAMINATIONS COUNCIL}

\title{
CRAFT CERTIFICATE IN INFORMATION TECHNOLOGY
}

\section*{MODULE I}

COMPUTFR APPIICAIIONSI
1 hour

\section*{INSTRUCTIONS TO THE CANDIDATES}

This paper consists of TEN questions.
Answer ALL the questions in the answer booklet provided.
Candidates should answer the questions in English.

This paper consists of 4 Printed pages.
Candidates should check the question paper to ascertain that all the pages are printed as indicated and that no questions are missing.
1. (a) With the aid of a diagram, differentiate between landscape and portrait page layouts as used in word processing documents.
(b) Explain the term worksheet as used in spreadshcet programs.
2. (a) Explain the function of textbox fealure as used in word processing programs.
(b) Explain the term data validation as applied in spreadsheet programs.
3. (a) Explain a reason why a database administrator would use a table template when creating a new database.
(b) Linnet intends to restrict access to part of the worksheet she was working on. Explain a spreadsheet feature she could apply to achieve her objective.
4. (a) Explain the function of the Esc key of a computer keyboard.
(b) A company with many branches prefers to use video conferencing to boardroom conferencing. Outline two reasons for their preference.
5. Figure 1 shows a section of a tool bar in a word processing application. Use it to answer the question that follows.
![](https://cdn.mathpix.com/cropped/2025_04_03_02e52bef732d075c170ag-2.jpg?height=178&width=450&top_left_y=1355&top_left_x=307)
(i)
(ii) (iii) (iv)

Figure 1
Identify each of the tools labeled (i), (ii), (iii) and (iv).
6. (a) Differentiate between primary and secondary files as used in a mail merge feature of a word processing program.
(2 marks)
:
(b) Explain a circumstance under which a many-to-many table relationship would be established in a database program.
(2 marks)
7. (a) Table 1 is an extract of a spreatsheet document showing the details of stafl payroll in a manufacturing company. Use it to answer the questions that follow.
\begin{tabular}{|c|c|c|c|c|c|}
\hline & A & B & C & D & E \\
\hline 1 & \multicolumn{4}{|c|}{Kilohyte Tank Producers Ltd} & \\
\hline 2 & & \multicolumn{2}{|l|}{Junc 2013 payroll} & & \\
\hline 3 & Staff No. & Staff Name & Basic Salary & \begin{tabular}{l}
House \\
Allowance
\end{tabular} & \begin{tabular}{l}
Gross \\
Salary
\end{tabular} \\
\hline 4 & 711 & Joseph ). & 15,000.00 & 2,250.00 & \\
\hline 5 & 516 & Jane K. & 25,000.00 & 5,400,00 & \\
\hline 6 & 372 & Mary A . & 17,000.00 & 3,250.00 & \\
\hline 7 & 819 & James L. & 11,500.00 & 2,100.00 & \\
\hline 8 & 526 & Grace J. & 18,900.00 & 4,300.00 & \\
\hline 9 & & & & & \\
\hline 10 & & & & & \\
\hline
\end{tabular}

Table 1
Write a formula that would be used to compute the Gross salary for Joseph.
(1 mark)
(b) Suppose the manager wanted the data in the worksheet arranged from the highest to the lowest paid staff and then alphabetically by Staff Names. Describe a spreadsheet feature he could use to achieve his objective.
8. (a) An examination database stores details of students who sat for an exam. Fach record has the following fields:
- Student II) Number
- The student passport sized photo
- Scores for each subject
- Total Fees Balance

State a suitable data type for each of the tields.
(2 marks)
(b) State the function of each of the following folders in an email program:
(i) inbox;
(ii) spam.
9. (a) Fxplain the function of slide sorter feature as used in presentation programs.
(b) A company which deals with the importation of second hand motor vehicles has a website with various hyperlinks. Explain the function of this feature on the website.
10. (a) Gerald intends to print a spreadsheet document with no gridlines shown on the print out. Describe the feature he would use to achieve his objective.
(b) Cate intends to change the object in figure 2 to resemble the object in figure 3.
![](https://cdn.mathpix.com/cropped/2025_04_03_02e52bef732d075c170ag-4.jpg?height=112&width=195&top_left_y=481&top_left_x=420)

Figure 2
![](https://cdn.mathpix.com/cropped/2025_04_03_02e52bef732d075c170ag-4.jpg?height=125&width=165&top_left_y=469&top_left_x=958)

Figure 3

Describe a presentation program feature she would use to achieve her objective.
--- Converted MMD End ---
