registerQuiz("topic-01-quiz", {
    "schemaVersion": "1.0",
    "quizId": "topic-01-quiz",
    "metadata": {
        "title": "Introduction to Disaster Management",
        "description": "Test your knowledge of basic definitions, disaster types, and predisposing factors.",
        "topicId": "topic-01",
        "difficulty": "beginner",
        "estimatedTime": 5,
        "passingScore": 70,
        "createdAt": "2025-12-25T12:00:00Z",
        "tags": ["definitions", "basics", "hazards"]
    },
    "settings": {
        "shuffleQuestions": true,
        "shuffleOptions": true,
        "showFeedback": "immediate",
        "allowRetry": true,
        "showCorrectAnswers": true
    },
    "questions": [
        {
            "id": "q1",
            "type": "multiple-choice",
            "question": "Which of the following best defines a 'Disaster' according to the WHO?",
            "points": 10,
            "options": [
                { "id": "a", "text": "Any event that causes economic loss", "isCorrect": false },
                { "id": "b", "text": "A sudden ecological phenomenon of sufficient magnitude to require external assistance", "isCorrect": true },
                { "id": "c", "text": "A situation generated by a real or imminent event requiring immediate attention", "isCorrect": false },
                { "id": "d", "text": "An event managed entirely by local resources", "isCorrect": false }
            ],
            "explanation": "WHO defines a disaster as a sudden ecological phenomenon of sufficient magnitude to require external assistance, exceeding the capacity of the affected community."
        },
        {
            "id": "q2",
            "type": "fill-blank",
            "question": "Risk is conceptually defined by the formula: Risk = __b1__ × __b2__.",
            "points": 10,
            "blanks": [
                { "id": "b1", "acceptedAnswers": ["hazard", "Hazard"], "caseSensitive": false },
                { "id": "b2", "acceptedAnswers": ["vulnerability", "Vulnerability"], "caseSensitive": false }
            ],
            "explanation": "Risk is the product of a Hazard (the potential event) and Vulnerability (the susceptibility to damage)."
        },
        {
            "id": "q3",
            "type": "matching",
            "question": "Match the term to its definition:",
            "points": 10,
            "pairs": [
                { "id": "p1", "left": "Hazard", "right": "A rare/extreme event affecting life/property" },
                { "id": "p2", "left": "Emergency", "right": "Situation requiring immediate attention but within coping capacity" },
                { "id": "p3", "left": "Mitigation", "right": "Permanent reduction of risk" },
                { "id": "p4", "left": "Preparedness", "right": "Measures ensuring organized mobilization of resources" }
            ]
        },
        {
            "id": "q4",
            "type": "multiple-select",
            "question": "Which of the following are considered 'Slow-onset' disasters? (Select all that apply)",
            "points": 10,
            "options": [
                { "id": "a", "text": "Earthquake", "isCorrect": false },
                { "id": "b", "text": "Drought", "isCorrect": true },
                { "id": "c", "text": "Famine", "isCorrect": true },
                { "id": "d", "text": "Desertification", "isCorrect": true }
            ],
            "partialCredit": true,
            "explanation": "Drought, famine, and desertification develop gradually over time, unlike earthquakes which are sudden-onset."
        }
    ]
});