Processing PDF: /home/ngobiro/projects/pngobiro.github.io/colleges/kmtc/diploma/DIAGNOSTIC IMAGING/10A. Level IV GIT Imaging.pdf
Starting PDF processing...
PDF processing started. ID: 2025_05_16_1a9238fe5dc2aa72656eg
Polling PDF status (ID: 2025_05_16_1a9238fe5dc2aa72656eg)...
Attempt 1: Status = split, Progress = 97.8%
Attempt 2: Status = completed, Progress = 100.0%
PDF processing completed successfully.
Fetching MMD result (ID: 2025_05_16_1a9238fe5dc2aa72656eg)...

--- Converted MMD Start ---

- \%S 5. VINB. VIRN, . . \# ., \$ I .\# . (/ CJ), . .. FE.(\%*3. )(/ CJ), . . 0 CD*NBH ( 1 JIB)
- \$ POINVBOU3 BEJPNEWIUBOE \$ BOAS *NBEWAH4QFDBNIU
- - FDXSFS, \%FQBSNFOUPG\%JBFOPTUD *NBEWAHBOE 3 BEJBUPO. FEIDAF, 6 OWFSIICZ PG/ BISPCJ.

0 \# +\&\$ 5*7 \&4
1. \%FILESTF UF NPEBMIFT BWBUNZW CPS (*5 JNBHOH
2. \%JIDVIT UF JOEIDBUPOF, LPOSBOEJIBUPOT BOE GBUFOU QFQBBUPO (PS FBE PGUF NPEBNIFT
3. ) JH NH UUF NNJWUPOT PGUF EFIDNGE JNBEJOH NPERMUIFT
4. 1SFIFOUFYNQMT PGBOBLPNJDBOE QBU PNWILEBMNBEFTBT ENPOIGBUE JOFBL PGUF NPEBNUFT
- $0 \% \& 40$, ( \#5 \% " (\%) (
1. 1N10SBEIPHSBQ Z
2. \$ POSBIUSBEIPFBBQ Z
3. 6 NBBIPVOE
4. \$ 5 4DBO
5. . 3 * 4DBO
6. 3 BEJPONDEF JNBHOH(/ VABS. FEIDCF)
7. " OHPHSBQ Z

\section*{1-"\% 3 " \%*0 ( 3 " 1 ) :}

\section*{- B10 FOFDBUPO}
- 1 NO SBEIPESBA TBFF GFRVPOUY TUNUF GSIUONFIUFBUPO JO UF

\section*{- B10- N, CBUPOT}
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-05.jpg?height=65&width=2387&top_left_y=835&top_left_x=448)
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-05.jpg?height=65&width=1817&top_left_y=886&top_left_x=512)
- 1 PPS TPGUTIVF IPGOSBIUI JOERST BDVSBZ PGERWDUCH EJIFBIF PVUJEF UF ( *5 NNFO

\section*{\$ BVUPO}
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-05.jpg?height=65&width=2455&top_left_y=1218&top_left_x=448)
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-05.jpg?height=65&width=2204&top_left_y=1269&top_left_x=510) QFIFOF PGBIS-GNIE NWWMIXI JII NBZ GF GOFD PS B QPUAYS W PCISVUIPO

1-"\% 3 " \%* ( 3 " 1 ) :
QSPKDUPOT

Supine AP projection
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-06.jpg?height=839&width=979&top_left_y=533&top_left_x=1930)

6 TVBM BERYBEF (PSERWDUAHFOFSBY *5 TBEVT
*OEIDBUE XI FONFLUCHCPSBS QMUE NWWMIX JUJO UF CPXFMPSFYGB CPXFMBT
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-07.jpg?height=111&width=1000&top_left_y=51&top_left_x=444)
$\square$
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-07.jpg?height=341&width=447&top_left_y=1080&top_left_x=440)

BU
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-07.jpg?height=1524&width=1149&top_left_y=301&top_left_x=1020)
$\square$
4PGUINET
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-07.jpg?height=320&width=528&top_left_y=1116&top_left_x=2258)

S BVICIRE TISVIVSIP?

\section*{" ODPN JOBYY-SBZ WALINBUDBOOSPBEI O POUPO 1}
- \$ I FLL UF QBUFOUERWMI
- " TIFIT RVBYZ (JODNEIOH QFIFOIF PGBSUCPLI).
- \# PXFMBT
- 4 PGUITVFT
" \# PQFT
- " COPSNBMBIVIGIBUPOT
\#F 4 WF \# FOPS "_DUPO!

\section*{" CDPN JOBMY-SBZ WALANBLDBOOSPBEI O POWPO 2}
- " JS
- \# PXFM
\% \% OID
- 0.5HBOT
- \&YUSOBYPGEDUT BOE BSWCPLIT
"\# \%0 9
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-10.jpg?height=1388&width=2585&top_left_y=97&top_left_x=346)
" SWC:RDT
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-11.jpg?height=1808&width=3322&top_left_y=57&top_left_x=6)

\section*{\# PXFM BT}

\section*{Intra-luminal}

\section*{Normal}
- Gastric bubble (erect film)
- Large bowel
- Very minimal or nondetectable in small bowel

\section*{Check for abnormalities}
- Size
- Distribution: peripheral-large bowel, central - small bowel
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-13.jpg?height=971&width=1731&top_left_y=144&top_left_x=895)
( BILISIDCVCAY
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-14.jpg?height=1278&width=1991&top_left_y=0&top_left_x=4)
/ PSNBM BSF CPXFMBT

\section*{"93 0" S \% \% IICXCVUPO}
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-15.jpg?height=1082&width=805&top_left_y=386&top_left_x=1018)
/ PSNBMGOEICHT
"\#/03."-*/53"-6.*/"-" *3 1"55\&3/:
- 0\$" - *4" 5*0 /
\begin{tabular}{|l|l|l|}
\hline Feature & \multicolumn{2}{|c|}{Obstruction} \\
\hline & Small bowel & Large bowel \\
\hline Bowel diameter (cm) & >3 and <5 & >5 \\
\hline Position of loops & Central & Peripheral \\
\hline Number of loops & Many & Few \\
\hline Fluid levels (on erect film) & Marry, short & Few, long \\
\hline Bowel markings & Valvaulae (all the way across) & Haustra (partially across) \\
\hline
\end{tabular}

Large bowel gas
No
Yes

\section*{"93 o BCOPSN BIV" JS \%JILSICVIPOO *OBSBINTIN JOBM}
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-17.jpg?height=1034&width=1942&top_left_y=427&top_left_x=531)

4 VQAC
4NBMMPXFMPCICSVUPO
\&FFDU

\section*{"93 o BCOPSN BIV' JS \%JILSICVUPO-JOSSBIN'N JOBM}
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-18.jpg?height=1421&width=1281&top_left_y=259&top_left_x=856)
- BYF CPXFMPCISYUIPO O TVQFF

\section*{"930" JS \%JILSYCVUPO JOKSBIN JOBMBCOPSN BM}
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-19.jpg?height=1066&width=2512&top_left_y=489&top_left_x=416)

1BSBYUID JNKY
4JFNPJE WPMMNMT
NFUPSIN

\section*{Bxtra-luminal}
- Always abnormal
- Key areas to look at
1.Subdiaphragmatic (erect film)
2.Bowel wall
3. Liver - portovenous, biliary.

\section*{![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-21.jpg?height=86&width=2161&top_left_y=106&top_left_x=442)}

SemiERECT
" JS WEAS UF EJBQ SBH

1 GFNPQFSIPOFW o THPOEBS W GEPPSBUE HU
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-22.jpg?height=974&width=1298&top_left_y=423&top_left_x=831)

3 JFNS TTHOO \%PVAVI XBYWIINO

1 GFNPGESIPOFW o THPOEBZ W QFSPSBUE HU

\section*{"930"\#/03. "- " S \%JILSTCVUPO-FYSBINTN JOBM}

1OFWPQFSIPOFWN o - UNGWSBYEFDVCIVT WFX
"930"\#/03. "- " JS \%』IICXCVUPOO \& 53 " - 6. * "-
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-24.jpg?height=1013&width=2306&top_left_y=548&top_left_x=514)

1 GFW BEPTIT JOWIUOBII
(JOSBNWBRY
" JSTI BWPOYA GLFOUXJUJ JOUF QPXFMPSJUP QF DPOIJEFSE OPSNBM
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-25.jpg?height=1107&width=2340&top_left_y=314&top_left_x=580)

\section*{" OE JOUF SHH LOPPQPSUPOT}
\begin{tabular}{|l|l|l|l|l|l|l|l|l|l|l|l|l|l|l|l|l|l|}
\hline \begin{tabular}{l}
1 \\
H
\end{tabular} & \multicolumn{16}{|c|}{} & \begin{tabular}{l}
2 \\
He
\end{tabular} \\
\hline 3 & \begin{tabular}{l}
4 \\
Be
\end{tabular} & \multirow[b]{3}{*}{\begin{tabular}{l}
21 \\
Sc
\end{tabular}} & & & & & & & & & & \begin{tabular}{l}
5 \\
B
\end{tabular} & \begin{tabular}{l}
6 \\
C
\end{tabular} & \begin{tabular}{l}
7 \\
N
\end{tabular} & \begin{tabular}{l}
8 \\
0
\end{tabular} & \begin{tabular}{l}
9 \\
F
\end{tabular} & \begin{tabular}{l}
10 \\
Ne
\end{tabular} \\
\hline 11 Na & \begin{tabular}{l}
12 \\
Mg
\end{tabular} & & & & & & & & & & & \begin{tabular}{l}
13 \\
Al
\end{tabular} & \begin{tabular}{l}
14 \\
Si
\end{tabular} & \begin{tabular}{l}
15 \\
P
\end{tabular} & \begin{tabular}{l}
16 \\
5
\end{tabular} & \begin{tabular}{l}
17, \\
Cl
\end{tabular} & \begin{tabular}{l}
18. \\
Ar
\end{tabular} \\
\hline 19 K & 20 Ca & & \begin{tabular}{l}
22 \\
Ti
\end{tabular} & \begin{tabular}{l}
23 \\
v
\end{tabular} & \begin{tabular}{l}
24 \\
Cr
\end{tabular} & \begin{tabular}{l}
25 \\
Mn
\end{tabular} & \begin{tabular}{l}
26 \\
Fe
\end{tabular} & \begin{tabular}{l}
27 \\
Co
\end{tabular} & \begin{tabular}{l}
28 \\
Ni
\end{tabular} & \begin{tabular}{l}
29 \\
Cu
\end{tabular} & \begin{tabular}{l}
30 \\
Zn
\end{tabular} & \begin{tabular}{l}
31 \\
Ga
\end{tabular} & \begin{tabular}{l}
32. \\
Ge
\end{tabular} & \begin{tabular}{l}
33 \\
As
\end{tabular} & \begin{tabular}{l}
34 \\
Se
\end{tabular} & \begin{tabular}{l}
35 \\
Br
\end{tabular} & \begin{tabular}{l}
36 \\
Kr
\end{tabular} \\
\hline 37 Rb & 38 Sr & 39 Y & 40 Zr & 41 Nb & 42 Mo & \begin{tabular}{l}
43 \\
Tc
\end{tabular} & \begin{tabular}{l}
44 \\
Ru
\end{tabular} & \begin{tabular}{l}
45 \\
Rh
\end{tabular} & \begin{tabular}{l}
46 \\
Pd
\end{tabular} & \begin{tabular}{l}
47 \\
Ag
\end{tabular} & \begin{tabular}{l}
48 \\
Cd
\end{tabular} & \begin{tabular}{l}
49 \\
In
\end{tabular} & \begin{tabular}{l}
50 \\
Sn
\end{tabular} & \begin{tabular}{l}
51 \\
Sb
\end{tabular} & \begin{tabular}{l}
52. \\
Te
\end{tabular} & \begin{tabular}{l}
53 \\
I
\end{tabular} & \begin{tabular}{l}
54 \\
Xe
\end{tabular} \\
\hline 55 Cs & & * & \begin{tabular}{l}
72 \\
Hf
\end{tabular} & \begin{tabular}{l}
73 \\
Ta
\end{tabular} & \begin{tabular}{l}
74 \\
w
\end{tabular} & \begin{tabular}{l}
75 \\
Re
\end{tabular} & \begin{tabular}{l}
76 \\
Os
\end{tabular} & \begin{tabular}{l}
77 \\
Ir
\end{tabular} & \begin{tabular}{l}
78 \\
Pt
\end{tabular} & \begin{tabular}{l}
79 \\
Au
\end{tabular} & \begin{tabular}{l}
80 \\
Hg
\end{tabular} & 3) Tl & 82 Pb & 83 Bi & 84 Po & 85 At & 86 Rn \\
\hline 87 87
Fr & 88 Ra & ** & & 105 Db & 106 Sg & 107 Bh & 108 Hs & 109 Mt & 110 Ds & 111 Uuu & 112 Uub & & & & & & \\
\hline
\end{tabular}
\begin{tabular}{|l|l|l|l|l|l|l|l|l|l|l|l|l|l|l|l|}
\hline \multirow[t]{2}{*}{Lanthanoids *} & 57 & 58 & 59 & 60 & 61 & 62 & 63 & 64 & 65 & 66 & 67 & 68 & 69 & 70 & 71 \\
\hline & La & Ce & Pr & Nd & Pm & Sm & Eu & Gd & Tb & Dy & Ho & Er & Tm & Yb & Lu \\
\hline \multirow[t]{2}{*}{Actinoids **} & 89 & 90 & 91 & 92 & 93 & 94 & 95 & 96 & 97 & 98 & 99 & 100 & 101 & 102 & 103 \\
\hline & Ac & Th & Pa & U & Np & Pu & Am & Cm & Bk & Cf & Es & Fm & Md & No & Lr \\
\hline
\end{tabular}

\section*{( \#5 \$ POGSBIU3 BEAPHSBOLZ}
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-27.jpg?height=741&width=490&top_left_y=446&top_left_x=2)

JH BRPNJDOWNGS NBEWSIBM
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-27.jpg?height=1247&width=2412&top_left_y=374&top_left_x=918)
- WIGBMIWEIFT

\section*{( \#5 \$ POGSBIU3 BEAPESBOLZ \\ 0. PABDURT}
t 4JBNILEBOLZ o TBNWMBZ HWOET
t \# B 4XBNóX o PFIPQ BHVT
t \# B. FBVD PFIPQ BHVT, TUPNBD, EVPEFON
t \# B. NFBMPMOX USPVH o P,T,E,TC
t 4NBN\# PXFM\&ORNB (\&OHSPDYITI)-TNBWOPXFM
t \# B. \&CFNB o NSHF CPXFM
t \$ PNIIGPHSBN, 4JCPHBRN, 'JLWNELEBN
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-28.jpg?height=1404&width=966&top_left_y=72&top_left_x=2366)

\section*{\# BTXBMMX}
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-30.jpg?height=1398&width=2586&top_left_y=250&top_left_x=138)
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-31.jpg?height=1486&width=1987&top_left_y=48&top_left_x=384)

1 esophagus 2 fundus of the stomach 3 body of the stomach 4 lesser curvature 5 greater curvature 6 pyloric antrum
7 pylorus 8 duodenal bulb (1st half of 1st stage of duodenum)
9 2nd stage of duodenum 10 3rd stage of duodenum
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-33.jpg?height=1396&width=1073&top_left_y=123&top_left_x=616)

4NBMMPXFMFOFNB FOHSPDYIIT
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-34.jpg?height=1412&width=1153&top_left_y=102&top_left_x=104)
\# B \&OFNB
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-34.jpg?height=967&width=1022&top_left_y=384&top_left_x=2236)

\section*{6 NESTPVOE JO( *5 *NBELOH}

5IPVI PGNNJWE WAWF JO JNBHOH UF ( *5, CPS UF SEBIPO UBU HBT QPEVAFT QPPS TPVE QFAFBBUPO, JUDBO CF VIFCMMO UF CPNUXJOH BSFBT
1. 4 VIQHWE NBIFT
2. 4 VIQHUE QFSIPGFBMANUE DPMALUPOT
3. 4 VIQHUE DBVINNT
4. 4 VIQFUFE JOOWNBENPZ DPOEJUPOTNLF BQQFOEIDUT
5. 4 VIQMUE JONIVIILEQUPO
6. 4 VIQFULE IFSOBT
7. 5 IF BBVOEJLEE QBUFOU

\section*{\$ PN QUUSJILE 5 PN PISBOL Z (\$ 5 ) JO (*5}
1. ( BOCH QPQWasy, BT JOWFIUIBUPO PGL PJLF JO BDVF BOEPNFO BOE ISBWA
2. \$ PNQVINFOUT PUFS SBEIPNWHIDBMICWEIFTPGUF ( *5 UP EFUSN JOF UF FYWOUPGEJIFBIF
3. \&WMMBHUF NFIFOHSZ, BERSFOUTPNE PSHBOT, UF QASUPOFBMBWLZ, BOE UF SFEPQASIPOFW
4. 4 URF NBYFOBODFT BOE FWWMBF CPS SFDSPODF
5. \$ 5 FOUSPLAIT P FWWMBF UF TNBWOPXFM
6. 7 JSWRYPOEPIDPQZ o \$ 5 \$ PNGPHSEQ Z IBT NUSHY

SPQMOE \# B FONB BIUE NBHTOHNPERNY, PGD PJIF
JONSFF CPXFMEIIFBIF. *UTRAP JOPSQPSBUE BTB
TD\&FOOH WPMPS DPMSFLEPMBSDCPNB JOI JH SIL HSPVQI.

\title{
\$ PNQVUSJILE 5 PN PISBQLZ (\$ 5 ) JO ( \#5
}

5 BF F OPW PGUF CPMUXJCH
1. \$ 5 JTSFNUWFAZ FYQFOINW BOE VOBWMYAY
2. \$ BVUPOIBT W QF WFOTAOF JUHWTI JH SEEIBUPO EPTF UP UF QBUFOU
\$ PN QVUSJIITE 5 PN PHSBQL Z (\$ 5 ) JO (\%
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-38.jpg?height=1090&width=1068&top_left_y=361&top_left_x=457)
/ PSNBYBOOFOEJY
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-38.jpg?height=1047&width=1273&top_left_y=408&top_left_x=1609)
" DVF BOOFOEIDUT

\section*{\$ PN QUUSJILE 5 PN PHSBOLZ (\$ 5 ) JO (*5}
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-39.jpg?height=1008&width=1332&top_left_y=389&top_left_x=397)
\$ BFDBYNBYHOBOUCNPYS
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-39.jpg?height=1005&width=1234&top_left_y=382&top_left_x=1701)
. FUBIGEUD NYFS NWIIPOT GPN \$ BLPNO

\section*{\$ PN QUUSJIIDE 5 PN PISBOLZ (\$ 5) JO ( *5}
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-40.jpg?height=1179&width=1162&top_left_y=406&top_left_x=737)
\$ 5 (WSUBYY IPNFOPTIPQZ) SFWFBMIB QPIZQ

5 I PVI NPSF FYQFOINF BOE NIIT BWBJNAY DPNQBSFE UP
UF NPEBNUIFT XF I BWF BIGBEZ EIIDVIIFE JUI BT UFIF
NBOBEWBOLPFT
1. \&YANWOUTPGUITVF DPOSBIU
2. / PO- JPOINOHSBEIBUPO
3. . WM- TFRYPOUBYN WM-QWOBS DBQBCINIIFT
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-41.jpg?height=82&width=1609&top_left_y=1243&top_left_x=854) OPUVIFE JOBDNF TFWOH

5 I PVI NPSF FYQFOINF BOE NIIT BWBJNAY DPNQBSFE UP
UF NPEBNUIFT XF I BWF BIGBEZ EIIDVIIFE JUI BT UFIF
NBOBEWBOLPFT
1. \&YANWOUTPGUITVF DPOSBIU
2. / PO- JPOINOHSBEIBUPO
3. . WM- TFRYPOUBYN WM-QWOBS DBQBCINIIFT
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-42.jpg?height=82&width=1609&top_left_y=1243&top_left_x=854) OPUVIFE JOBDNF TFWOH

\section*{" OFIPHSBOL Z JO ( \#5}
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-43.jpg?height=1085&width=1047&top_left_y=444&top_left_x=782)

\section*{. BO SPM JT JO DPNCJOFE EIBHOPTUDBOE JOWSWFOUPOBM NBHOH}

3 JH UDPNDBULSZ FYGBWBIBUPO
PGIPOSBIUENPOIGBUCH QPJOU
PGI FNPSS BFF
- *7 \&3 " / \% \# * *' 3: 53" \$ 5 * " (* (o 1 \& 5 (104*530/ \& *44*0/ 50.0 (3"1) : )
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-44.jpg?height=886&width=1039&top_left_y=467&top_left_x=518)
![](https://cdn.mathpix.com/cropped/2025_05_16_1a9238fe5dc2aa72656eg-44.jpg?height=90&width=2212&top_left_y=1452&top_left_x=561) NGOF PGUF NWFS
--- Converted MMD End ---
