Processing PDF: /home/ngobiro/projects/pngobiro.github.io/colleges/tvet/diploma/Diploma in Electrical and Electronic Engineering - Power Option./Entrepreneurship education/pastpapers/knec/2023j.pdf
Starting PDF processing...
PDF processing started. ID: 2025_04_28_ab5e18418a1d8f6101f4g
Polling PDF status (ID: 2025_04_28_ab5e18418a1d8f6101f4g)...
Attempt 1: Status = split, Progress = 40.0%
Attempt 2: Status = completed, Progress = 100.0%
PDF processing completed successfully.
Fetching MMD result (ID: 2025_04_28_ab5e18418a1d8f6101f4g)...

--- Converted MMD Start ---
![](https://cdn.mathpix.com/cropped/2025_04_28_ab5e18418a1d8f6101f4g-1.jpg?height=264&width=234&top_left_y=535&top_left_x=875)

\section*{THE KENYA NATIONAL EXAMINATIONS COUNCIL}

\title{
DIPLOMA IN MECHANICAL ENGINEERING (PRODUCTION, PLANT AND CONSTRUCTION PLANT OPTIONS) DIPLOMA IN AUTOMOTIVE ENGINEERING DIPLOMA IN WELDING AND FABRICATION DIPLOMA IN ELECTRICAL AND ELECTRONIC ENGINEERING (POWER, TELECOMMUNICATIONS AND INSTRUMENTATION OPTIONS) DIPLOMA IN BUILDIVG DIPLOMA IN CIVIL ENGINEERING DIPLOMA IN ARCHITECTURE
}

\section*{MODULE I}

INFORMATION COMMUNICATION TECHNOLOGY, COMMUNICATION SKILLS AND ENTREPRENEURSHIP EDUCATION

\section*{3 hours}

\section*{INSTRUCTIONS TO CANDIDATES}

You should the following for this examination:
Answer booklet;
Scientific calculator/Mathematical table.
This paper consists of TWELVE questions in THREE sections; $\boldsymbol{A}, \boldsymbol{B}$ and $\boldsymbol{C}$.
Answer FOUR questions from section A, answer question SIX (compulsory) and any other ONE question from section $\boldsymbol{B}$ and any THREE questions from section $\boldsymbol{C}$.
Maximum marks for each part of a question are indicated.
Candidates should answer the questions in English.

\section*{This paper consists of 5 printed pages.}

Candidates should check the question paper to ascertain that all the pages are printed as indicated and that no questions are missing.

\section*{SECTION A: INFORMATION COMMUNICATION TECHNOLOGY (40 marks) \\ Answer any FOUR questions in this section.}
1. (a) Explain the way in which each of the following categories of input devices enter data in a computer:
(i) pointing;
(ii) scanning.
(b) Explain the function of each of the following features in spreadsheet applications:
(i) wrap text;
(ii) merge cells;
(iii) sort.
2. (a) Outline four features of Wide Area Networks (WANs).
(b) Explain the circumstance under which each of the following database objects may be used:
(i) report;
(ii) query;
(iii) form.
3. (a) Distinguish between normal layout view and slide sorter view with respect to presentation software.
(b) Explain three functions of a computer operation system.
4. (a) Figure 1 shows icons used in desktop publishing software.
\begin{tabular}{|l|l|l|}
\hline \multirow{2}{*}{(i)} & ![](https://cdn.mathpix.com/cropped/2025_04_28_ab5e18418a1d8f6101f4g-2.jpg?height=121\&width=151\&top_left_y=1787\&top_left_x=814) & ![](https://cdn.mathpix.com/cropped/2025_04_28_ab5e18418a1d8f6101f4g-2.jpg?height=121\&width=124\&top_left_y=1787\&top_left_x=1073) \\
\hline & (ii) & (iii) \\
\hline
\end{tabular}

Explain the function of each icon.
(b) Outline four features of microcomputer.
\begin{tabular}{lllll}
$2501 / 101$ & $2508 / 101$ & $2602 / 101$ & $2707 / 101$ & 2 \\
$2502 / 101$ & $2509 / 101$ & $2603 / 101$ & $2709 / 101$ & \\
$2503 / 101$ & $2601 / 101$ & $2705 / 101$ & $2710 / 101$ & \\
June'July 2023 & & &
\end{tabular}
5. (a) Explain each of the following terms as used in data security:
(i) $\log$ files;
(ii) authentication.
(b) The following document about The Education Sector was created using a word processing application.

The education sector in Kenya has realized several aehievements in the integration of technology. It has embraced the sharing of knowledge outside the physical
![](https://cdn.mathpix.com/cropped/2025_04_28_ab5e18418a1d8f6101f4g-3.jpg?height=52&width=1234&top_left_y=668&top_left_x=513) and more. This has revolutionized the conventional method of chalk and board style of learning imparted to the students.

The use of technology in education has made teaching and learning to become simpler, easier, and more effective.
(i) identify four formatting features applied on the document.
(ii) explain the command that would be used to search for the word 'education' in the document.

\section*{SECTION B: COMMUNICATION SKILLS (30 marks)}

Answer question SIX (compulsory) and any other ONE question from this section.
6. (a) Outline three indicators of a poorly written essay.
(b) State two ways in which a receiver may exhibit etiquette during a telephone conversation.
(c) Some managers prefer to use written communication when conveying information to employees. State three reasons that may account for this preference.
(d) Distinguish between lateral communication and diagonal communication. (4 marks)
(e) Highlight three benefits that an engineering firm may derive from effective interpersonal communication.
(f) Outline three ways in which information communication technology (ICT) may promote effective business communication.
(g) State two strategies that may be adopted in an organization to enhance the loyalty of a new customer.
7. (a) The management of Sifa Engineering Works has noted reduced upward communication. Explain two measures that may be taken to address this situation.
(b) With the aid of an illustration, outline the steps involved in the process of communication.
8. (a) Explain three activities that the chairperson should carry out in preparation for a meeting.
(b) An interviewer may form certain perceptions from an interviewee's appearance. Outline two such perceptions.
(c) Explain the reason that makes it necessary to use each of the following features in a power point presentation:
(i) images;
(ii) bullets.

\section*{SECTION C: ENTREPRENEURSHIP EDUCATION (30 marks) \\ Answer any THREE questions from this section.}
9. (a) Outline four functions served by the business description section of a business plan.
(4 marks)
(b) Distinguish between limited liability and unlimited liability as used in business ownership.
(c) State two ways in which an entrepreneur may benefit from agency banking services.
(2 marks)
10. (a) Highlight three advantages of keeping electronic records in a business organization.
(3 marks)
(b) Outline four benefits that may be associated with the growth of entrepreneur-ship in a country.
(c) Jack recently left salaried employment to become self employed. State three reasons that may have informed this decision.
11. (a) Paza Limited intends to promote its newly launched product through sales promotion. Highlight four advantages of this method of promotion.
(b) Outline four reasons that may lead to failure of a business during the start-up phase.
(c) Explain the term 'innovation' as used in entrepreneurship.
12. (a) Explain two purposes served by carrying out a pre-feasibility study of a business opportunity.
(b) State three ways in which a business organization may be socially responsible towards each of the following stakeholders:
(i) suppliers;
(ii) employees.

\section*{THIS IS THE LAST PRINTED PAGE.}
\begin{tabular}{lllll}
$2501 / 101$ & $2508 / 101$ & $2602 / 101$ & $2707 / 101$ & 5 \\
$2502 / 101$ & $2509 / 101$ & $2603 / 101$ & $2709 / 101$ & \\
$2503 / 101$ & $2601 / 101$ & $2705 / 101$ & $2710 / 101$ &
\end{tabular}
--- Converted MMD End ---
