Processing PDF: /home/ngobiro/projects/pngobiro.github.io/colleges/tvet/diploma/Diploma in Electrical and Electronic Engineering - Power Option./Entrepreneurship education/pastpapers/knec/july2015.pdf
Starting PDF processing...
PDF processing started. ID: 2025_04_28_764c80bcb2275a5f9693g
Polling PDF status (ID: 2025_04_28_764c80bcb2275a5f9693g)...
Attempt 1: Status = split, Progress = 0.0%
Attempt 2: Status = split, Progress = 40.0%
Attempt 3: Status = split, Progress = 80.0%
Attempt 4: Status = completed, Progress = 100.0%
PDF processing completed successfully.
Fetching MMD result (ID: 2025_04_28_764c80bcb2275a5f9693g)...

--- Converted MMD Start ---
$\qquad$ Index No: $\qquad$

Candidate's Signature: $\qquad$

Date: $\qquad$ INFORMATION COMMUNICATION TECHNOLOGY, COMMUNICATION SKILLS AND ENTREPRENEURSHIP EDUCATION

\section*{INSTRUCTIONS TO CANDIDATES}

Write your name and index number in the spaces provided above.
Sign and write the date of examination in the spaces provided above.
This paper consists of THREE Sections; $\boldsymbol{A}, \boldsymbol{B}$ and $C$.
Answer FOUR questions in Section A, question 6 (compulsory) and ONE other questions in Section B and THREE questions from Section C in the spaces provided in this question paper. All questions carry equal marks.
Maximum marks for each part of a question are as indicated.
Candidates should answer the questions in English.
For Examiner's Use Only
\begin{tabular}{|l|l|l|l|}
\hline Section & Question & Maximum Score & Candidate's Score \\
\hline \multirow{4}{*}{A} & & 10 & \\
\hline & & 10 & \\
\hline & & . 10 & \\
\hline & & 10 & \\
\hline \multirow{2}{*}{B} & 6 (compulsory) & 20 & \\
\hline & & 10 & \\
\hline \multirow{3}{*}{C} & & 10 & \\
\hline & & 10 & \\
\hline & & 10 & \\
\hline \multicolumn{2}{|r|}{TOTAL SCORE} & 100 & \\
\hline
\end{tabular}

This paper consists of 20 printed pages.
Candidates should check the question paper to ascertain that all the pages are printed as indicated and that no questions are missing.

\section*{SECTION A: INFORMATION COMMUNICATION TECHNOLOGY}

Answer FOUR questions in this section.
1. (a) Explain the function of the following devices on a computer:
(i) keyboard;
(ii) monitor.
(b) Outline two characteristics of magnetic disks.
![](https://cdn.mathpix.com/cropped/2025_04_28_764c80bcb2275a5f9693g-2.jpg?height=256&width=544&top_left_y=507&top_left_x=1301)
(c) With the aid of a sketch explain the Universal Serial Bux (BUS) port.
(d) Distinguish between the following utility software programs:
(i) linker;
(ii) loader
2. (a) Explain the following computer terms as used in computer crime:
(i) hacking; binouthorisext accesf of other reafie ipycmacuol - -ithmang (ii) piracy. 'llegar gopy, ing, disoribuera or useop Sof (3 marks)
(b) Jaribu Supermarkets have networked their computers in their chain of business enterprises. Explain three characteristics these computers are likely to exhibit if they are infected with a virus.
(c) Essolom Enterprises specialise in reorganisation and restructuring of their clients' filing systems. Advise them on the suitability of the following file organisation methods:
(i) sequential;
(ii) random.
(d) Describe the following in Database Management Systems:
(i) query;
(ii) table.
3. (a) Differentiate between the following terminologies:
(i) Electronic Funds Transfer (EFT);
(ii) Internet banking.
(b) Explain two advantages of using robots in the industry in this information technology age.
(c) Mount Kenya Institute has been spending a lot of money when responding to regular mails from students making enquiries on their programs. As a consultant, outline three benefits that the Institute could enjoy if it used electronic mails instead of regular mails.
(d) Joel Magana, an ICT specialist has decided to interlink his hospitals with the clinics of City Hall. Identify two suitable devices to enable him carry out the connection.
4. (a) Define the term 'topology' as used in computer networking.
(b) KIM traders have linked their businesses using Ring Topology. As a consultant, explain two possible causes of failure of the system.
(c) With the aid of diagrams, explain the differences between Analogue data and Digital data signals.
(d) Describe the following terminologies for data transmission:
(i) address bus;
(ii) data bus;
(iii) control bus.
![](https://cdn.mathpix.com/cropped/2025_04_28_764c80bcb2275a5f9693g-3.jpg?height=373&width=616&top_left_y=1109&top_left_x=1425)
5. (a) Explain the term 'spreadsheet' as used in computer software.
(b) Explain the techniques for copying data from one location to another in a spreadsheet program.
(c) Makini Groceries would like to audit its inventory. the management is in the process of purchasing software packages to do this. As a specialist advise them on three considerations they should make before they embark on any spending.
(d) Distinguish between the following terminologies for computer networks:
(i) multi-user;';
(ii) multi-tasking
6. (a) Huduma Kwa Vijana organises workshops on HIV/AIDS sensitization. You have been appointed to make a short presentation at the workshop:
(i) state the software program that will be suitable for your presentation;
(ii) highlight the procedure for preparing your program in a(i) above.
\begin{tabular}{lll}
$2501 / 101$ & $2601 / 101$ & $2707 / 101$ \\
$2502 / 101$ & $2602 / 101$ & $2709 / 101$ \\
$2503 / 101$ & $2603 / 101$ & $2710 / 101$ \\
$2509 / 101$ & $2705 / 101$ &
\end{tabular}
(b) Describe the procedure used to add a Word Art element to a publication.
(c) Taalam and Taalam Associates are intending to prepare a database that will consolidate all the proceedings in the High Court. Explain the procedure they are likely to use to create a database using a database wizard.
(3 marks)

\section*{SECTION B: COMMUNICATION SKILLS}

\section*{Answer question 6 and ONE other question in this section.}
6.
(a) Outline three components of a communication situation.
(b) State two consequences of sending incomplete information to a recipient.
(c) State three benefits of effective internal communication in an organisation.
(d) Explain two ways in which the arrangement of a room may positively influence communication during a meeting.
(e) State two timutations of not having an organisation chart in an organisation.
(f) Outline three principles that may be followed in designing effective notices.
(g) The management of Imani Engineering Works Limited conducts appraisal interviews annually. Explain the importance of such interviews for the organisation.
(h) State three essentials of effective communication.
7. (a) The first item of business at most meetings is the formal agreement that the minutes of the last meeting are a true and accurate record of what happened. Explain the importance of this procedure.
(b) John Mawingu recently joined Uwezo Limited as an engineer. As the Communication Assistant, write a letter introducing him to Baraka Engineering Works where the organisation is currently carrying out a project.
8. (a) Explain the meaning of the following types of customers who may visit businesses:
(i) need-based customers;
(ii) loyal customers.
(b) State six situations that may make a manager opt to use oral means of communication.
(6 marks)

\section*{SECTION C: ENTREPRENEURSHIP EDUCATION}

Answer any THREE questions from this section.
9. (a) (i) 8 Explain the meaning of the term 'window of opportunity' in entrepreneurship.
(ii) State four considerations that an entrepreneur should make when evaluating the
![](https://cdn.mathpix.com/cropped/2025_04_28_764c80bcb2275a5f9693g-5.jpg?height=130&width=175&top_left_y=1096&top_left_x=553) viability of a business opportunity.
(b) Outline four guidelines that the management of an enterprise may follow in order to be effective in social responsibility activitiès.
10. - (a) State four benefits that an individual may derive from self employment.
(b) Outline six reasons that make business planning an important aspect in entrepreneurship.
11. . (a) Highlight four attributes that a successful entrepreneur should possess.
(b) Small and medium size enterprises have Been on the rise in Kenya. State six contributions of these enterprises to the economic development of the country.
12. (a) Outline four characteristics of the recovery stage of the business life cycle.
(b) Explain three benefits that may accrue to an organisation that out-sources services.
\begin{tabular}{lll}
$2501 / 101$ & $2601 / 101$ & $2707 / 101$ \\
$2502 / 101$ & $2602 / 101$ & $2709 / 101$ \\
$2503 / 101$ & $2603 / 101$ & $2710 / 101$ \\
$2509 / 101$ & $2705 / 101$ &
\end{tabular}
--- Converted MMD End ---
