Processing PDF: /home/ngobiro/projects/pngobiro.github.io/colleges/tvet/diploma/Diploma in Electrical and Electronic Engineering - Power Option./Entrepreneurship education/pastpapers/knec/july2019.pdf
Starting PDF processing...
PDF processing started. ID: 2025_04_28_4657bde2dfa6900833c0g
Polling PDF status (ID: 2025_04_28_4657bde2dfa6900833c0g)...
Attempt 1: Status = completed, Progress = 100.0%
PDF processing completed successfully.
Fetching MMD result (ID: 2025_04_28_4657bde2dfa6900833c0g)...

--- Converted MMD Start ---
\begin{tabular}{llll}
$2501 / 101$ & $2508 / 101$ & $2602 / 101$ & $2707 / 101$ \\
$2502 / 101$ & $2509 / 101$ & $2603 / 101$ & $2709 / 101$ \\
$2503 / 101$ & $2601 / 101$ & $2705 / 101$ & $2710 / 101$
\end{tabular}

INFORMATION COMMUNICATION TECHNOLOGY, COMMUNICATION SKILLS AND ENTREPRENEURSHIP EDUCATION

\section*{THE KENYA NATIONAL EXAMINATIONS COUNCIL}

\title{
DIPLOMA IN MECHANICAL ENGINEERING (PRODUCTION), (PLANT OPTION), (CONSTRUCTION PLANT OPTION) DIPLOMA IN AUTOMOTIVE ENGINEERING DIPLOMA IN WELDING AND FABRICATION DIPLOMA IN ELECTRICALAND ELECTRONIC ENGINEERING (POWER, TELECOMMUNICATIONS AND INSTRUMENTATION OPTIONS) DIPLOMA IN BUILDING \\ DIPLOMA IN CIVIL ENGINEERING DIPLOMA IN ARCHITECTURE
}

\author{
MODULE I \\ INFORMATION COMMUNICATION TECHNOLOGY, COMMUNICATION SKILLS AND ENTREPRENEURSHIP EDUCATION
}

3 hours

\section*{INSTRUCTIONS TO CANDIDATES}

This paper consists of EIGHT questions in THREE sections; $\boldsymbol{A}, \boldsymbol{B}$ and $\mathbf{C}$.
Answer FOUR questions from section A, question SIX (Compulsory) and one other question from section $B$ and THREE questions from section $C$.
All answers should be written in the answer booklet provided.
Maximum marks for each part of a question are as indicated.
Candidates should answer the questions in English.

This paper consists of 5 printed pages.
Candidates should cheek the question paper to ascertain that all the pages are printed as indicated and that no questions are missing.

\section*{SECTION A: INFORMATION COMMUNICATION TECHNOLOGY}

Answer any FOUR questions from this section.
1. (a) Explain each of the following terms:
(i) computer network;
(ii) multi-user computer.
(b) On the computer keyboard, there are some keys that appear twice where one set is to the left of the keyboard and the other set is to the right of the keyboard.
(i) State two such keys.
(ii) Explain the reason for having such arrangement for those particular keys on the keyboard.
2. (a) Distinguish between installing software and launching software.
(b) Outline the steps of creating a folder on the desktop of a personal computer.
(c) State three ways in which audit trails may help improve data security.
3. (a) An employee noted that the words typed in the upper case had spelling mistakes despite having a spelling and grammar checker in word processing.
(i) Explain the reason for this;
(ii) State the steps that should be followed to ensure that the spell checker is helpful in correcting the words in upper case.
(b) State the purpose of each of the following features in word processing programs:
(i) thesaurus;
(ii) caption.
\begin{tabular}{llll}
$2501 / 101$ & $2508 / 101$ & $2602 / 101$ & $2707 / 101$ \\
$2502 / 101$ & $2509 / 101$ & $2603 / 101$ & $2709 / 101$ \\
$2503 / 101$ & $2601 / 101$ & $2705 / 101$ & $2719 / 101$
\end{tabular}
(c) The cells M5 to M25 in a spreadsheet program contain grades of students in an examination. State the spreadsheet formula that should be used to display each of the following:
(i) the number of students who scored grade A;
(ii) the total number of students in the entire list;
(iii) the total number of students who scored grades $A$ and $B$.
4. (a) State two benefits of using cables in a local area network instead of using wireless links.
(b) With the aid of examples, explain the use of each of the following operators in databases:
(i) AND
(ii) OR
(c) An employee was trying to open an email but had forgotten the password. Outline the process of regaining access to the email.
5. (a) Outline the process of designing staff business cards by use of a desktop publishing program.
(b) A motivational speaker intends to set presentation slides to run automatically. State the steps that should be followed to achieve this objective.
(c) Some banks have introduced card less banking on their ATMs. However, the ATMs still have card slots. Explain two advantages of running the ATM card services alongside the card-less ATM services.

\section*{SECTION B: COMMUNICATION SKILLS}

Answer question 6 (COMPULSORY) and ONE other question from this section.
6. (a) Explain each of the following phrases as used in communication:
(i) active listening;
(ii) communication flow.
(b) Explain the way in which each of the following barriers to effective communication may be minimized in an organization:
(i) wrong choice of medium;
(ii) information overload;
(iii) human relations.
(c) Write an essay of about 250 words on the topic, "The Importance of Budgeting in a Business Enterprise".
7. (a) State four elements of the terms of reference of an investigative report.
(b) Explain three responsibilities of the chairperson before a meeting.
8. (a) Outline four characteristics of an effective poster as a medium of communication.
(b) Highlight three advantages of asking probing questions during an interview.
(c) State three roles of the public relations department in an organization.
\begin{tabular}{llll}
$2501 / 101$ & $2508 / 101$ & $2602 / 101$ & $2707 / 101$ \\
$2502 / 101$ & $2509 / 101$ & $2603 / 101$ & $2709 / 101$ \\
$2503 / 101$ & $2601 / 101$ & $2705 / 101$ & $2710 / 101$
\end{tabular}

\section*{SECTION C: ENTREPRENEURSHIP EDUCATION}

Answer THREE questions from this section.
9. (a) Explain each of the following attributes of a successful entrepreneur:
(i) open-mindedness;
(ii) human relations.
(b) Some business enterprises make use of social media to communicate with its external stakeholders. Explain three challenges that an enterprise may face as a result of this use.
10. (a) Outline four factors that an entrepreneur may consider when choosing a form of business ownership.
(b) Explain three circumstances that may compel an individual to become self employed.
11. (a) State four limitations of a business plan.
(b) Explain three types of costs that may be associated with labour turnover in a business enterprise.
12. (a) Outline four ways in which parents may foster the spirit of entrepreneurship in their children.
(b) (i) Explain the phrase business idea.
(ii) State four criteria that a good business opportunity should meet.

\section*{THIS IS THE LAST PRINTED PAGE.}
--- Converted MMD End ---
