Processing PDF: /home/ngobiro/projects/pngobiro.github.io/colleges/kmtc/diploma/Diploma in Clinical Medicine and Surgery/Community Health/pastpapers/UNPROCESSED/COMMUNITY HEALTH MOCK 2013 P2-1.pdf
Starting PDF processing...
PDF processing started. ID: 2025_12_01_6661e39d59021c387cecg
Polling PDF status (ID: 2025_12_01_6661e39d59021c387cecg)...
Attempt 1: Status = split, Progress = 92.9%
Attempt 2: Status = completed, Progress = 100.0%
PDF processing completed successfully.
Fetching MMD result (ID: 2025_12_01_6661e39d59021c387cecg)...

--- Converted MMD Start ---
\section*{INSTRUCTIONS}
1. Write you index number in the spaces provided in the answer sheet
2. Time allowed is 3 hours
3. Attempt all questions

\section*{4. Do not use a pencil}
5. Answer all questions on the answer sheet provided by marking " x " against the appropriate response for either true or false
6. You score one mark for every correct response
7. You will be penalized one mark (minus 1 mark) for every wrong response
8. You do not score or loose any mark for not responding to the questions
9. All cancellations must be clean and complete

\section*{QUESTIONS}
1) About growth and development of children: -
a) In a normal infant, the head circumference equals the chest circumference up to the age of 1 year
b) Adequate play is important in helping physical, mental and social development
c) Allowing a child independence facilitates emotional development
d) Imaginative play in children in important in reducing anger and fear
e) Children require plenty of room to facilitate discovery of things during their development

\begin{tabular}{|c|c|c|c|c|}
\hline F & T & T & T & T \\
\hline
\end{tabular}
2) The following developmental in language and social behavior milestones are correctly matched with their respective age(s): -
a) 1 month - can follow objects and make loud noises
b) 3-6 months - grasps actively
c) 9-12 months - able to stand
d) 2 years - can say several words or even sentences
e) 3 years - child is clever in climbing and jumping

\begin{tabular}{|c|c|c|c|c|}
\hline F & T & F & T & T \\
\hline
\end{tabular}
3) Predisposing factors to child abuse include: -
a) Cultural practices
b) War
c) Famine
d) Drug and substance abuse
e) Insecurity

\begin{tabular}{|c|c|c|c|c|}
\hline T & T & T & T & T \\
\hline
\end{tabular}
4) The following are live vaccines: -
a) BCG
b) Measles
c) Polio
d) Pentavalent
e) Hepatitis B

\begin{tabular}{|l|l|l|l|l|}
\hline T & T & T & F & F \\
\hline
\end{tabular}
5) About observation research: -
a) The observer can seek clarification or explanations on a certain phenomenon under study
b) The observer controls or manipulates the subjects in participant observation
c) Participant observation gives valid information
d) Simulation observation allows the observer to observe required behavior
e) Ethnography involves intensive data collection on many variables over an extended period of time

\begin{tabular}{|l|l|l|l|l|}
\hline F & F & T & T & T \\
\hline
\end{tabular}
6) Factors influencing food choices: -
a) Habits
b) Culture
c) Social status
d) Physical appearance of an individual
e) Emotional comfort

\begin{tabular}{|c|c|c|c|c|}
\hline T & T & T & T & T \\
\hline
\end{tabular}
7) Regarding birth injuries: -
a) Caput succedaneum is a large swelling caused by bleeding between membrane covering the outside of a skull and limited to one skull bone
b) Subdural haematoma causes increased intracranial pressure and bulging of the fontanel
c) Erb's palsy involves damage to the brachial plexus nerves
d) Cephalohaematoma should be aspirated
e) Caput succedaneum should be aspirated

\begin{tabular}{|l|l|l|l|l|}
\hline F & T & T & F & \\
\hline
\end{tabular}
8) Complications of tonsillitis and pharyngitis include: -
a) Otitis media
b) Peritonsilar abscess
c) Rheumatic fever
d) Tonsillolith
e) Cervical lymphadenitis

\begin{tabular}{|c|c|c|c|c|}
\hline T & T & T & T & T \\
\hline
\end{tabular}
9) Changes that occur in a family due to illness of a member include: -
a) Role changes
b) Change in social customs
c) Loneliness
d) Financial constraints
e) Task reassignments

\begin{tabular}{|c|c|c|c|c|}
\hline T & T & T & T & T \\
\hline
\end{tabular}
10)Major characteristics of Freud's stages of personality development include: -
a) Between the ages of 12 months -3 years children exhibit the Oedipal complex
b) Between 5-6 years of age sexual concerns are paramount
c) From birth t- 18 months children attain gratification from suckling, eating, mouthing and biting
d) In the phallic stage identify with same-sex parents
e) During adolescence and adulthood establishment of mature sexual relationships is evident

\begin{tabular}{|l|l|l|l|l|}
\hline T & T & T & F & F \\
\hline
\end{tabular}
11) In the social intervention model on health education: -
a) Postulates that people prefer to do things commonly done by their community
b) Explains that reliance on one method leads to likely failures
c) Advocates for knowledge and understanding of interaction between cultural, biological, physical and social environment
d) Focuses on interest, evaluation and adoption (acceptance)
e) Is not based on recognition and treatment of disease

\begin{tabular}{|c|c|c|c|c|}
\hline T & T & T & F & T \\
\hline
\end{tabular}
12) With regard to educational theories in community health: -
a) Behavioural theory utilizes reinforcement and punishment
b) Social learning theory requires provision of information
c) Cognitive theory seeks to change thought patterns
d) Developmental theory focuses on behavior change
e) Humanist theory explains the influence that feelings, emotions and personal relationships have on behavior

\begin{tabular}{|l|l|l|l|l|}
\hline T & T & T & F & T \\
\hline
\end{tabular}
13)A good questionnaire should
a) Be short and simple
b) Have questions in a logical sequence
c) Have a variety of questions
d) Have technical terms
e) Not contain personal and intimate questions

\begin{tabular}{|l|l|l|l|l|}
\hline T & T & T & F & F \\
\hline
\end{tabular}
14)Features of a population pyramid of a developed country include a.......:-
a) Wider middle
b) Narrow base
c) Wide base
d) Narrow middle
e) Wider top

\begin{tabular}{|l|l|l|l|l|}
\hline T & T & F & F & F \\
\hline
\end{tabular}
15)Characteristics of stage I of the demographic cycle include: -
a) High birth rates
b) High death rates
c) Slow and fluctuating population growth
d) High population growth
e) Association with industrial stage

\begin{tabular}{|c|c|c|c|c|}
\hline T & T & T & F & F \\
\hline
\end{tabular}
16) With regard to a constrictive population pyramid: -
a) Has a low crude death rate
b) Life expectancy is high
c) Is exhibited by developed countries
d) Shows high crude birth rate
e) Seen in countries with high fertility rates

\begin{tabular}{|l|l|l|l|l|}
\hline T & T & F & F & F \\
\hline
\end{tabular}
17)Advantages of note taking during interviews: -
a) Facilitates data analysis
b) Limits omissions
c) Hastens the interview process
d) Enhances rapport
e) Reinforces responses to personal and sensitive questions

\begin{tabular}{|c|c|c|c|c|}
\hline T & T & F & F & F \\
\hline
\end{tabular}
18)About communicating to a dying person; -
a) Allows dying persons to make arrangements for the survivors
b) Gives them an opportunity to participate in funeral and burial arrangements
c) Individuals have an opportunity to reminisce and converse with important people in their life's
d) Is an important cultural practice
e) Focuses on internal growth other than mental pathology and preparation for death

\begin{tabular}{|c|c|c|c|c|}
\hline T & T & T & T & T \\
\hline
\end{tabular}
19)Forms of mourning at funerals in Kenya:-
a) Wearing of a black arm band
b) Ceremonial meals
c) 21 gun salute
d) Cultural and traditional dances e.g. mock fights, eshiremba (Luhya)
e) Draping of the casket in a national or institutional flag

\begin{tabular}{|c|c|c|c|c|}
\hline T & T & T & T & T \\
\hline
\end{tabular}
20) Invisible fat is found in: -
a) Soya beans
b) Egg yolk
c) Groundnuts
d) Butter
e) Fatty meat

\begin{tabular}{|l|l|l|l|l|}
\hline T & T & T & F & F \\
\hline
\end{tabular}
21)Features of rickets include: -
a) Protruding abdomen
b) Oedema of the legs
c) Curling of long bones
d) Narrow chest
e) Box shaped head

\begin{tabular}{|l|l|l|l|l|}
\hline F & F & T & T & T \\
\hline
\end{tabular}
22)Regarding digestion of food nutrients: -
a) Most of the hydrolysis of triglycerides occurs in the stomach
b) Large units of fatty acids easily diffuse into the intestinal cells
c) Chemical and enzymatic digestion of proteins begins in the mouth
d) The major site for digestion of protein is in the small intestines
e) Fibre is not digested in the stomach and delays gastric emptying

\begin{tabular}{|l|l|l|l|l|}
\hline F & F & F & F & T \\
\hline
\end{tabular}
23)Refuse disposal method not recommended in a hospital set-up: -
a) Composite pit
b) Sanitary land fill
c) Organized dumping
d) Controlled burning
e) Placenta pit

\begin{tabular}{|l|l|l|l|l|}
\hline T & T & T & F & F \\
\hline
\end{tabular}
24)Contraindications of combine oral contraceptives: -
a) Hypertension
b) Valvular heart disease
c) Severe headache
d) Pelvic infections
e) Vaginal discharge

\begin{tabular}{|l|l|l|l|l|}
\hline T & T & T & F & F \\
\hline
\end{tabular}
25) Warning of teen substance abuse include: -
a) Red and glazed eyes
b) Personality change
c) Poor judgment
d) Low self esteem
e) Depression

\begin{tabular}{|c|c|c|c|c|}
\hline T & T & T & T & T \\
\hline
\end{tabular}
26)Genital discharge is associated with: -
a) Gonorrhea
b) Candidiasis
c) Trichomoniasis
d) Syphilis
e) Chancroid

\begin{tabular}{|l|l|l|l|l|}
\hline T & T & T & F & F \\
\hline
\end{tabular}
27)Scabies: -
a) Is caused by infestation by a male mite
b) The mite burrow deep into the skin producing intense itchiness
c) Presents with a generalize skin rash
d) Transmission is by direct contact and through clothes and beddings
e) Scalp and feet are affected only in infants under one year of age

\begin{tabular}{|l|l|l|l|l|}
\hline F & F & F & T & T \\
\hline
\end{tabular}
28) Regarding Tineasis: -
a) Griseofulvin is the drug of choice
b) Tinea unguium is best treated with topical applications for a period of 6 weeks
c) Topical applications for ten days are effective in treatment of Tinea pedis
d) Duration of treatment for Tinea capitis is $6-12$ weeks
e) Talcum powder is useful in Tinea cruris

\begin{tabular}{|l|l|l|l|l|}
\hline T & F & F & T & T \\
\hline
\end{tabular}
29)Stage III of trachoma:
a) Entropion is a feature
b) The eyes are red and watery mimicking ordinary conjunctivitis
c) Conjunctiva has whitish scars
d) Scar tissue develops in the cornea
e) Pre-auricular glands are enlarged

\begin{tabular}{|c|c|c|c|c|}
\hline F & T & T & F & F \\
\hline
\end{tabular}
30)Features associated with WHO stage III of HIV/AIDS for adults/adolescents: -
a) Oral candidiasis
b) HIV encephalopathy
c) Kaposis sarcoma
d) Herpes zoster
e) Severe weight loss and unexplained chronic diarrhoea

\begin{tabular}{|l|l|l|l|l|}
\hline T & F & F & F & T \\
\hline
\end{tabular}
31)Risk factors for pre-eclampsia and eclampsia: -
a) Maternal age
b) Low socioeconomic status
c) Sociocultural beliefs and practices
d) Lack of awareness
e) Poor infrastructure

\begin{tabular}{|c|c|c|c|c|}
\hline T & T & T & T & T \\
\hline
\end{tabular}
32)Protease inhibitors(PIs) include: -
a) Ritonavir
b) Nelfinavir
c) Nevirapine
d) Efavirenz
e) Zidovudine

\begin{tabular}{|l|l|l|l|l|}
\hline T & T & F & F & F \\
\hline
\end{tabular}
33)Factors influencing health seeking behavior in the community include: -
a) Cultural beliefs
b) Socio-economic status
c) Women empowerment
d) Gender roles
e) Economic status

\begin{tabular}{|c|c|c|c|c|}
\hline T & T & T & T & T \\
\hline
\end{tabular}
34)The following vectors are correctly matched with respective diseases they transmit: -
a) Anopheles funestus
- malaria
b) Glossina palpalis
- river blindness
c) Simulium damnosum
- trypanosomiasis
d) Phlebotomus spp
- kala azar
e) Aedes spp
- yellow fever

\begin{tabular}{|l|l|l|l|l|}
\hline T & F & F & T & T \\
\hline
\end{tabular}
35)In amoebic dysentery: -
a) Incubation period is relatively short
b) Exhibits generalized abdominal tenderness
c) Fever is a common feature
d) Patients have severe tenesmus
e) Stools have blood and mucous

\begin{tabular}{|l|l|l|l|l|}
\hline F & F & F & F & T \\
\hline
\end{tabular}
36)Factors enhancing domestic violence: -
a) Culture
b) Social organization of the family
c) Power inequality
d) Family inequality
e) Family privacy

\begin{tabular}{|c|c|c|c|c|}
\hline T & T & T & T & T \\
\hline
\end{tabular}
37) Differentiating features of food poisoning from cholera: -
a) Vomiting is watery and projectile causing no distress
b) Muscular cramps are constant and severe
c) Diarrhoea precedes vomiting
d) Diarrhoea follows vomiting
e) Tenesmus is common

\begin{tabular}{|l|l|l|l|l|}
\hline F & F & F & T & T \\
\hline
\end{tabular}
38)About hookworm infestation: -
a) Can present with murmurs and CCF
b) An adult N. americanas cause a daily blood loss of 0.5 mls per worm per day
c) Development of anaemia is rapid
d) Proper disposal of feaces is important in prevention and control
e) Blood transfusion is highly recommend

\begin{tabular}{|l|l|l|l|l|}
\hline T & F & F & T & T \\
\hline
\end{tabular}
39)Causes of spousal violence: -
a) Economic conditions
b) Verbal aggression
c) Inadequacy of husbands
d) Changing gender rules
e) Family history

\begin{tabular}{|l|l|l|l|l|}
\hline T & T & T & T & T \\
\hline
\end{tabular}
40)About Rabies; -
a) Incubation period is influenced by site of bite and distance of wound from the brain
b) Furious rabies is associated with violent behavior and convulsions
c) Depression is a feature of paralytic rabies
d) Recovery is the rule
e) Hydrophobia is associated with furious rabies

\begin{tabular}{|l|l|l|l|l|}
\hline T & T & T & F & F \\
\hline
\end{tabular}
41)Predisposing factors to meningococcal meningitis: -
a) Overcrowding
b) Mastoiditis
c) Malnutrition
d) Head injury
e) Epidemic of measles

\begin{tabular}{|l|l|l|l|l|}
\hline T & F & F & F & F \\
\hline
\end{tabular}
42)Features of rubella: -
a) Microphthalmia
b) Deafness
c) Microcephaly
d) Mental retardation
e) Jaundice

\begin{tabular}{|c|c|c|c|c|}
\hline T & T & T & T & T \\
\hline
\end{tabular}
43)Primary prevention of blindness in children includes: -
a) Nutritious food rich in vitamin a to the mother
b) VDRL test during pregnancy
c) Administration of vitamin A to the child
d) Safe delivery
e) Improvement of safety of toys

\begin{tabular}{|l|l|l|l|l|}
\hline T & T & T & T & F \\
\hline
\end{tabular}
44)Common domestic accidents include: -
a) Poisoning
b) Burns
c) Drowning
d) Falls
e) Bites and injuries from animals

\begin{tabular}{|c|c|c|c|c|}
\hline T & T & T & T & T \\
\hline
\end{tabular}
45)In the community development approach to health promotion: -
a) Empowers individuals to make healthy choices
b) Operates in a "top-down" approach
c) Utilizes participatory learning techniques
d) Embraces socio-economic and environmental causes of ill health
e) Is grounded on experiences and perspectives of communities

\begin{tabular}{|l|l|l|l|l|}
\hline F & F & F & T & T \\
\hline
\end{tabular}
46)In communication, mass media includes: -
a) Television
b) Radio
c) News papers
d) Brochures
e) Posters

\begin{tabular}{|c|c|c|c|c|}
\hline T & T & T & F & F \\
\hline
\end{tabular}
47)Emerging global challenges facing community health include: -
a) Technological advances
b) Environmental degradation
c) Food insecurity
d) Increased consumer awareness
e) Emerging diseases

\begin{tabular}{|c|c|c|c|c|}
\hline T & T & T & T & T \\
\hline
\end{tabular}
48)Fast onset hazards include: -
a) Earthquakes
b) Storm water and cyclones
c) Pest infestation
d) Drought and famine
e) Environmental degradation

\begin{tabular}{|l|l|l|l|l|}
\hline T & T & T & F & F \\
\hline
\end{tabular}
49)On hospital waste management: -
a) Pathological wastes are stored in red liner bags
b) Sharps are stored in boxes and jericans
c) Clinical waste is stored in white liner bags
d) Food remains are stored in yellow liner bags
e) General waste is stored in white liner bags

\begin{tabular}{|l|l|l|l|l|}
\hline T & T & F & F & F \\
\hline
\end{tabular}
50)Principles of managing communicable disease include: -
a) Attacking the source
b) Interrupting transmission
c) Immunization
d) Better nutrition
e) Vector control

\begin{tabular}{|l|l|l|l|l|}
\hline T & T & F & F & F \\
\hline
\end{tabular}

\begin{tabular}{|l|l|l|l|l|l|}
\hline & a & b & C & d & e \\
\hline 1. & T & T & T & T & T \\
\hline 2. & T & F & F & F & F \\
\hline 3. & T & T & T & T & T \\
\hline 4. & F & T & T & T & T \\
\hline 5. & F & T & F & T & T \\
\hline 6. & T & T & T & T & T \\
\hline 7. & T & T & T & F & F \\
\hline 8. & F & F & T & T & T \\
\hline 9. & T & T & T & T & T \\
\hline 10. & T & F & F & F & F \\
\hline 11. & T & T & T & T & T \\
\hline 12. & F & T & T & F & \\
\hline 13. & T & T & T & T & T \\
\hline 14. & T & T & T & T & T \\
\hline 15. & T & T & T & F & F \\
\hline 16. & T & T & T & T & T \\
\hline 17. & T & F & F & F & F \\
\hline 18. & T & T & T & F & F \\
\hline 19. & T & T & T & F & T \\
\hline 20. & T & F & F & T & F \\
\hline 21. & T & T & T & F & F \\
\hline 22. & F & T & T & T & F \\
\hline 23. & T & T & T & F & T \\
\hline 24. & T & T & T & F & T \\
\hline 25. & F & F & T & T & T \\
\hline 26. & T & T & T & F & F \\
\hline 27. & T & T & F & F & F \\
\hline 28. & T & T & T & T & F \\
\hline 29. & T & T & T & T & T \\
\hline 30. & T & F & F & T & T \\
\hline 31. & T & T & T & F & F \\
\hline 32. & F & T & T & F & T \\
\hline 33. & T & T & T & T & T \\
\hline 34. & T & T & T & F & F \\
\hline 35. & T & T & T & T & F \\
\hline 36. & T & T & F & F & F \\
\hline 37. & T & T & T & F & F \\
\hline 38. & T & T & T & F & F \\
\hline
\end{tabular}

\begin{tabular}{|l|l|l|l|l|l|}
\hline 39. & T & T & T & T & T \\
\hline 40. & T & T & F & F & F \\
\hline 41. & T & T & F & F & F \\
\hline 42. & F & F & T & T & T \\
\hline 43. & F & T & T & T & T \\
\hline 44. & T & T & T & F & F \\
\hline 45. & T & T & T & F & F \\
\hline 46. & T & T & T & F & F \\
\hline 47. & T & T & T & T & T \\
\hline 48. & T & T & F & F & F \\
\hline 49. & T & T & T & T & T \\
\hline 50. & T & T & T & T & T \\
\hline 51. & F & F & T & T & T \\
\hline 52. & T & T & T & T & T \\
\hline 53. & T & T & F & F & F \\
\hline 54. & T & T & T & F & F \\
\hline 55. & T & T & T & F & F \\
\hline 56. & F & F & T & T & T \\
\hline 57. & T & F & F & F & F \\
\hline 58. & T & T & T & T & T \\
\hline 59. & F & F & F & F & T \\
\hline 60. & T & T & T & F & F \\
\hline 61. & T & T & T & F & F \\
\hline 62. & F & F & T & T & T \\
\hline 63. & T & F & F & F & F \\
\hline 64. & T & T & T & F & F \\
\hline 65. & T & T & T & T & T \\
\hline 66. & T & T & T & F & F \\
\hline 67. & F & F & F & T & T \\
\hline 68. & T & F & F & T & T \\
\hline 69. & F & T & T & F & F \\
\hline 70. & T & F & F & F & T \\
\hline 71. & T & T & T & T & T \\
\hline 72. & T & T & F & F & F \\
\hline 73. & T & T & T & T & T \\
\hline 74. & T & F & F & T & T \\
\hline 75. & F & F & F & F & T \\
\hline 76. & T & T & T & T & T \\
\hline 77. & F & F & F & T & T \\
\hline 78. & T & F & F & T & T \\
\hline 79. & T & T & T & T & T \\
\hline 80. & T & T & T & F & F \\
\hline 81. & T & F & F & F & F \\
\hline 82. & T & T & T & T & T \\
\hline 83. & T & T & T & T & F \\
\hline 84. & T & T & T & T & T \\
\hline 85. & F & F & F & T & T \\
\hline 86. & T & T & T & F & F \\
\hline 87. & T & T & T & T & T \\
\hline 88. & T & T & T & F & F \\
\hline
\end{tabular}

\begin{tabular}{|c|c|c|c|c|c|}
\hline 89. & T & T & F & F & F \\
\hline 90. & T & T & F & F & F \\
\hline 91. & & & & & \\
\hline
\end{tabular}
--- Converted MMD End ---
