Processing PDF: /home/ngobiro/projects/pngobiro.github.io/colleges/kmtc/diploma/Diploma in Health Records and Information Technology/Year 1/Computer Application in Health Care/pastpapers/UNPROCESSED/2_PDFsam_Database Management Revision Questions - Final Exam DHR1001.pdf
Starting PDF processing...
PDF processing started. ID: 2025_11_27_1d9791e1348a6dd317a5g
Polling PDF status (ID: 2025_11_27_1d9791e1348a6dd317a5g)...
Attempt 1: Status = completed, Progress = 100.0%
PDF processing completed successfully.
Fetching MMD result (ID: 2025_11_27_1d9791e1348a6dd317a5g)...

--- Converted MMD Start ---
KENYA MEDICAL TRAINING COLLEGE

\section*{FACULTY OF MEDICAL EDUCATION AND INFORMATION TECHNOLOGY DEPARTMENT OF HEALTH RECORDS AND INFORMAION}

\section*{FINAL QUALIFYING EXAMINATION}

\section*{\section*{FOR} \\ DIPLOMA IN HEALTH RECORDS AND INFORMATION TECHNOLOGY}

PAPER: DATABASE MANAGEMENT (THEORY)

DATE: $9{ }^{\text {th }}$ June 2022
TIME: 45 MINUTES (8:00 AM - 8:45AM)

\section*{INSTRUCTIONS}
1. This paper consists of:
- Section 1 (40 Multiple Choice Questions)
- Section 2 (8 Short Answer Questions)
- Section 3 (1 Long Answer Question)
2. Attempt ALL Questions
3. Write the EXAMINATION NUMBER given on all the answer sheets provided and on the question paper.
4. Ensure that all examination answer scripts are handed in at the end of the examination
5. Ensure you sign the examination register provided

\section*{EXAMINATION NUMBER}

\section*{SECTION ONE: MULTIPLE CHOICE QUESTIONS (30 MARKS)}
1. The database designed to consist of multiple table that are linked together through matching data stored in each table is called $\_\_\_\_$
A. Object oriented database
B. Hierarchical database
C. Relational database
D. Network database
2. In E-R diagram attributes are represented by:
A. Triangle
B. Square
C. Rectangle
D. Ellipse
3. Count function in SQL returns the number of $\_\_\_\_$
A. Groups
B. Distinct values
C. Columns
D. Values
4. The statement in SQL which allows change of the definition of a table is $\_\_\_\_$
A. Select
B. Update
C. Alter
D. Create
5. What is the advantage of the database management approach?
A. Data redundancy increases
B. Data is integrated and can be accessed by multiple programs
C. Data is dependent on programs
D. None of the above
6. Which term is Row synonymous with?
A. Field
B. Column
C. Record

\section*{D. Relation}
7. In a one to many relationship, the entity that is on the one side of the relationship is called a $\_\_\_\_$ entity.
A. Parent
B. Child
C. Instance
D. Subtype
8. What is the SQL command to create a table?
A. Make table
B. Define table
C. Alter table
D. Create table
9. In database management, what do you mean by one to many relationship between student and class table?
A. One class may have many students
B. Many classes may have many classes
C. Many students may have many classes
D. One student can have many classes
10. To set a password, you first need to open the database in
A. Password
$\_\_\_\_$ mode.
B. Sharing
C. Exclusive
D. Read Only
11. Referential integrity means:
A. Do not enter value in the primary key field of a child table if that value does not exist in the primary key of the parent table
B. Do not enter a value in the foreign key field of a parent table if that value does not exist in the primary key of the child table
C. Do not enter a value in the foreign key field of a child table if that value does not exist in the primary key of the parent table.
D. All of the above
12. Which of the following data types is used to attach Microsoft files, graphics files, sound files and pdf files to a table?
A. Memo
B. Hyperlink
C. OLE Object
D. Text
13. $\_\_\_\_$ is a collection of related fields?
A. Record
B. File
C. Database
D. Relation
14. A technique used to search a data warehouse looking for related information and patterns is known as
$\_\_\_\_$ data.
A. One to one relationship
B. One to many relationship
C. Many to many relationship
D. Many to one relationship
15. The database design that consist of multiple tables that are linked together through matching data stored in each table is called a $\_\_\_\_$
A. Object oriented database
B. Hierarchical database
C. Relational database
D. Network database
16. In a relational schema, each tuple is divided into fields called:
A. Domains
B. Queries
C. Relations
D. All of the above
17. In database management, what do you mean by one to many relationships between student and class table?
A. One class may have many students
B. Many classes may have many classes
C. Many students may have many classes
D. One student can have many classes
18. To set a password, you first need to open the database in $\_\_\_\_$ mode.
A. Password
B. Sharing
C. Exclusive
D. Read Only
19. The relationship between a DEPARTMENT and EMPLOYEE is a $\_\_\_\_$ relationship>
A. One to one
B. One to many
C. Many to many
D. Many to one
20. The database design that consist of multiple table that are linked together through matching data stors in each table is referred to as:
A. Object oriented database
B. Hierarchical database
C. Relational database
D. Network database
21. In E-R diagram attributes are represented by:
A. Triangle
B. Square
C. Rectangle
D. Ellipse
22. The statement in SQL which allows to change the definition of table is?
A. Select
B. Update
C. Alter
D. Create
23. Row is synonymous with the term $\_\_\_\_$
A. Field
B. Column
C. Record
D. Relation
24. Entities can be associated with one another in which of the following ways?
A. Identifiers
B. Entities
C. Relationships
D. Attributes
25. Which of the following are five built in functions provided by SQL?
A. SUM, AVG, MIN, MAX, MULT
B. COUNT, SUM, AVG, MAX, MIN
C. SUM, AVG, MULT, DIV, MIN
D. SUM, AVG, MIN, MAX, NAME
26. What is the purpose of query?
A. Input data
B. Output data
C. Sort and filter
D. All of the above
27. Which of the following creates a drop down list of values to choose from?
A. Look up wizard
B. OLE Objects
C. Memo
D. Hyperlink
28. Which field type will you select if you need to enter long text in that field?
A. Text
B. Memo
C. Currency
D. Hyperlink
29. Which of the following is not a type of MS Access data base object?
A. Table
B. Form
C. Worksheets
D. Modules
30. In which method don't we need to specify the field type and size while creating a new Table?
A. Design View
B. While using Wizard
C. Create Table By Entering Data
D. All of Above
--- Converted MMD End ---
