#!/usr/bin/env python3
"""
AI Configuration Builder for StudoCU Scraper
Takes a natural language description and builds the config.py file.
"""

import os
import re
import json
import google.generativeai as genai
from typing import Dict, Any

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

# Template for config.py to ensure we preserve structure
CONFIG_TEMPLATE = '''#!/usr/bin/env python3
"""
Shared configuration for StudoCU scraper and download checker.
Auto-generated by build_config.py based on user request.
"""

# ============================================================================
# COURSE CONFIGURATION - For AI Context Understanding
# ============================================================================

COURSE_NAME = "{course_name}"
ACADEMIC_LEVEL = "{academic_level}"

# ============================================================================
# SEARCH CONFIGURATION
# ============================================================================

SEARCH_QUERY = "{search_query}"

# Institution ID (6230 is KMTC, set to None for global search)
INSTITUTION_ID = {institution_id}

# Course ID (optional)
COURSE_ID = {course_id}

# ============================================================================
# OUTPUT CONFIGURATION
# ============================================================================

import re
# Generate clean filename from search query
_clean_name = re.sub(r'[^\w\s-]', '', SEARCH_QUERY.lower())
_clean_name = re.sub(r'[-\s]+', '_', _clean_name)[:200]

OUTPUT_JSON = f"studocu_{{_clean_name}}_documents.json"
OUTPUT_CSV = f"studocu_{{_clean_name}}_documents.csv"

DOWNLOADS_DIR = "./downloads"

# ============================================================================
# URL CONSTRUCTION
# ============================================================================

from urllib.parse import quote
_encoded_query = quote(SEARCH_QUERY)
_params = []

if INSTITUTION_ID:
    _params.append(f"institutionId={{INSTITUTION_ID}}")
if COURSE_ID:
    _params.append(f"courseId={{COURSE_ID}}")

if _params:
    BASE_URL = f"https://www.studocu.com/en-us/search/{{_encoded_query}}?p=1&{{'&'.join(_params)}}"
else:
    BASE_URL = f"https://www.studocu.com/en-us/search/{{_encoded_query}}?p=1"

# ============================================================================
# SCRAPER SETTINGS
# ============================================================================

MAX_PAGES = {max_pages}
HEADLESS = {headless}
TIMEOUT = 30
PAGE_LOAD_WAIT = 3
BETWEEN_PAGE_DELAY = 3
'''

class ConfigBuilder:
    def __init__(self):
        self.api_key = os.environ.get('GEMINI_API_KEY')
        if not self.api_key:
            print("Error: GEMINI_API_KEY not found. Please set it in .env")
            exit(1)
        genai.configure(api_key=self.api_key)
        self.model = genai.GenerativeModel('gemini-2.0-flash')

    def get_institution_id_from_web(self, institution_name: str) -> str:
        """Search Google for the correct Studocu institution ID"""
        if not institution_name or institution_name.lower() in ['none', 'null']:
            return "None"
            
        print(f"🌍 Searching web for ID of: {institution_name}...")
        
        try:
            # Import tools for search
            from googleapiclient.discovery import build
            service = build("customsearch", "v1", developerKey=self.api_key)
            
            # Search query
            query = f"site:studocu.com {institution_name} institution id"
            res = service.cse().list(q=query, cx="b2812d777555b4698", num=3).execute()
            
            # Look for ID in URL or snippets
            # URLs look like: https://www.studocu.com/en-us/institution/kenya-medical-training-college/6230
            for item in res.get('items', []):
                link = item.get('link', '')
                match = re.search(r'/institution/[^/]+/(\d+)', link)
                if match:
                    found_id = match.group(1)
                    print(f"   ✓ Found ID: {found_id} (from URL)")
                    return f'"{found_id}"'
                    
            print("   ⚠️  ID not found in top results. Defaulting to None.")
            return "None"
            
        except Exception as e:
            print(f"   ❌ Search failed: {e}")
            return "None"

    def analyze_requirements(self, user_input: str) -> Dict[str, Any]:
        """Convert natural language to config parameters"""
        print("🧠 Analyzing your requirements with Gemini AI...")
        
        prompt = f"""You are a configuration generator for a Studocu educational document scraper (Kenya context).
User Request: "{user_input}"

Extract or generate the following parameters. Return ONLY a JSON object.

1. search_query: A SHORT, SMART, KEYWORD-FOCUSED search query (3-5 words max). 
   - Good: "KMTC Nursing FQE", "Anatomy Physiology Year 1"
   - Bad: "I want to find exam papers for nursing..."
   - If user asks for KMTC, include "KMTC" in query.
   
2. course_name: A descriptive name for the course/program (e.g. "Diploma in Nursing"). Guess if not explicit.

3. academic_level: The year/level mentioned (e.g. "Year 1 Sem 2", "Final Year", "FQE").

4. institution_id: 
   - If you KNOW the ID (e.g. KMTC=6230), provide it.
   - If the user mentions a specific university/college but you DON'T know the ID, return "SEARCH_WEB: <Institution Name>" (e.g. "SEARCH_WEB: Mount Kenya University").
   - If no specific institution is mentioned, return null.

5. max_pages: 
   - If user implies "sample" or "test" or "quick", set to 1 or 2.
   - If user implies "all" or "everything", set to null (Python None).
   - Default to null.

6. headless: boolean (True/False). Default False unless user says "background" or "silent".

JSON Structure:
{{
  "search_query": "string",
  "course_name": "string",
  "academic_level": "string",
  "institution_id": "string_or_SEARCH_WEB: Name_or_null",
  "course_id": null,
  "max_pages": "integer_or_null",
  "headless": boolean
}}
"""
        response = self.model.generate_content(prompt)
        try:
            # Clean response to get just JSON
            text = response.text.strip()
            if '```json' in text:
                text = text.split('```json')[1].split('```')[0]
            elif '```' in text:
                text = text.split('```')[1].split('```')[0]
            
            data = json.loads(text)
            
            # Post-process Institution ID
            inst_id = data.get('institution_id')
            if inst_id and str(inst_id).startswith("SEARCH_WEB:"):
                # Trigger web search
                inst_name = str(inst_id).split("SEARCH_WEB:")[1].strip()
                data['institution_id'] = self.get_institution_id_from_web(inst_name)
            elif inst_id is None or str(inst_id).lower() == 'null':
                data['institution_id'] = "None"
            else:
                data['institution_id'] = f'"{inst_id}"'
                
            if data.get('course_id') is None:
                data['course_id'] = "None"
            
            if data.get('max_pages') is None:
                data['max_pages'] = "None"
                
            data['headless'] = str(data.get('headless', False))
            
            return data
            
        except Exception as e:
            print(f"Error parsing AI response: {e}")
            print(f"Raw response: {response.text}")
            return None

    def build_config(self, data: Dict[str, Any], output_file: str = "config.py"):
        """Write the configuration file"""
        try:
            content = CONFIG_TEMPLATE.format(**data)
            with open(output_file, 'w') as f:
                f.write(content)
            print(f"✅ Configuration saved to {output_file}")
            print(f"   Query: {data['search_query']}")
            print(f"   Institution: {data['institution_id']}")
            return True
        except Exception as e:
            print(f"Error writing config: {e}")
            return False

def main():
    import sys
    
    print("AI Config Builder")
    print("-----------------")
    
    if len(sys.argv) > 1:
        user_input = " ".join(sys.argv[1:])
    else:
        user_input = input("Describe what documents you need (e.g. 'Nursing exams year 1 kmtc'): ")
    
    if not user_input:
        print("No input provided.")
        return
        
    builder = ConfigBuilder()
    params = builder.analyze_requirements(user_input)
    
    if params:
        builder.build_config(params)
        print("\n🚀 You can now run the scraper: ./venv/bin/python3 selenium_studocu_scraper.py")

if __name__ == "__main__":
    main()
