#!/usr/bin/env python3
"""
Shared configuration for StudoCU scraper and download checker.
Auto-generated by build_config.py based on user request.
"""

# ============================================================================
# COURSE CONFIGURATION - For AI Context Understanding
# ============================================================================

COURSE_NAME = "Nursing"
ACADEMIC_LEVEL = "Year 1 Sem 2"

# ============================================================================
# SEARCH CONFIGURATION
# ============================================================================

SEARCH_QUERY = "KMTC Nursing Year 1 exams"

# Institution ID (6230 is KMTC, set to None for global search)
INSTITUTION_ID = "6230"

# Course ID (optional)
COURSE_ID = None

# ============================================================================
# OUTPUT CONFIGURATION
# ============================================================================

import re
# Generate clean filename from search query
_clean_name = re.sub(r'[^\w\s-]', '', SEARCH_QUERY.lower())
_clean_name = re.sub(r'[-\s]+', '_', _clean_name)[:200]

OUTPUT_JSON = f"studocu_{_clean_name}_documents.json"
OUTPUT_CSV = f"studocu_{_clean_name}_documents.csv"

DOWNLOADS_DIR = "./downloads"

# ============================================================================
# URL CONSTRUCTION
# ============================================================================

from urllib.parse import quote
_encoded_query = quote(SEARCH_QUERY)
_params = []

if INSTITUTION_ID:
    _params.append(f"institutionId={INSTITUTION_ID}")
if COURSE_ID:
    _params.append(f"courseId={COURSE_ID}")

if _params:
    BASE_URL = f"https://www.studocu.com/en-us/search/{_encoded_query}?p=1&{'&'.join(_params)}"
else:
    BASE_URL = f"https://www.studocu.com/en-us/search/{_encoded_query}?p=1"

# ============================================================================
# SCRAPER SETTINGS
# ============================================================================

MAX_PAGES = None
HEADLESS = False
TIMEOUT = 30
PAGE_LOAD_WAIT = 3
BETWEEN_PAGE_DELAY = 3
