Processing PDF: /home/ngobiro/projects/pngobiro.github.io/colleges/tvet/certificate/Craft Certificate in Information Technology/Computer Application I (Practical)/pastpapers/knec/2015july.pdf
Starting PDF processing...
PDF processing started. ID: 2025_04_03_2ac19fb50e031e41107bg
Polling PDF status (ID: 2025_04_03_2ac19fb50e031e41107bg)...
Attempt 1: Status = split, Progress = 60.0%
Attempt 2: Status = split, Progress = 90.0%
Attempt 3: Status = completed, Progress = 100.0%
PDF processing completed successfully.
Fetching MMD result (ID: 2025_04_03_2ac19fb50e031e41107bg)...

--- Converted MMD Start ---
1920/102B

\section*{COMPUTER APPPLICATIONS 1 (PRACTICAL)}

Paper 2
July 2015
Time: 2 hours
![](https://cdn.mathpix.com/cropped/2025_04_03_2ac19fb50e031e41107bg-01.jpg?height=290&width=279&top_left_y=421&top_left_x=1050)

\section*{THE KENYA NATIONAL EXAMINATIONS COUNCIL.}

\section*{CERTIFICATE IN INFORMATION TECHNOLOGY}

MODULE I

\title{
COMPUTER APPLICATIONS I (PRACTICAL)
}

Paper 2
2 hours

\section*{INSTRUCTIONS TO CANDIDATES:}

You have ten minutes to read through the instructions and questions before starting the examination. Any problem with the computer should be reported to the invigilator immediately.
Direct any question(s) to the imvigilator only. Conversing with fellow students may lead to disqualification.
Write your name and index mumber on the answer booklet and the renritable CD.
Type your name as a heoder on each sheet used.
Answer all the FOUR questions.
Each question carries 15 marks.
Read the instructions of each question carefully.
Print on one side of the paper(s) only and use a fresh sheet of paper for ench question Hand over your printouts and the rewritable (D to the invigilalor:

\section*{SPECIFIC INSTRUCTIONS TO CANDIDATE}
1. Create a folder named KNECEXAMINDEXNO on the desktop where Index No is the students Index Number assigned in this exumination.
2. Ensure that the KNECEXAMINDEXNO folder created and all its content is burnt onto the Rewritable CD at the end of the examination.

TASK I
The management of Lentice company wishes to send invoices to clients who owe the company. Assuming that you have been tasked to prepare the invoices in a word processor using the mail merge feature
(a) Open word processing package and create a data source file containing the details of clients to be invoiced as shown in table 1.Save the document as invoicedatasource in the
KNECEXAMINDEXNO.
\begin{tabular}{|c|c|c|c|c|c|c|c|c|}
\hline First Name & Last Name & \begin{tabular}{l}
Company \\
Name
\end{tabular} & Hean 1 & Item2 & Amount & Ameunt2 & Date 1 & Date2 \\
\hline Jub & Joncs & Maringa Youtb Polytochnic & Alunkets & Matireases & 250.000 & 320,000 & 1705/2014 & 10/11/2014 \\
\hline Andrew & Marita & Mudayi Youfh Polytechaic & Sugar & Maize & 100,000 & 200,400 & 1803/2014 & 17/08/2014 \\
\hline Arn & Tomny & \begin{tabular}{l}
Ndencle \\
Youds \\
Polytechmic
\end{tabular} & Gamer kit & Halls & 150,000 & 220,006 & 19,40/2014 & 19098/2014 \\
\hline Paul & Lintons & \begin{tabular}{l}
Shembe \\
Youth \\
Polytechnic
\end{tabular} & Desktop computers & Computer thens & 500,060 & 250,000 & 22/12/2014 & $28 / 102014$ \\
\hline
\end{tabular}

Table 1
(b) Open a blank word document and type the following main document letter, inserting appropriate fields in their specified location.
( $81 / 2$ marks)
![](https://cdn.mathpix.com/cropped/2025_04_03_2ac19fb50e031e41107bg-03.jpg?height=342&width=696&top_left_y=1413&top_left_x=727)

Att: «First Names idast Namen
"Company Nome»
In respect to the goods issued to you, we hereby request that you make the payments as follows:
\begin{tabular}{|c|c|c|}
\hline & & \\
\hline citem_1\% & "Amount_1\% & "date 1\% \\
\hline uttem 2\% & "Amount 2\% & *date 2\% \\
\hline
\end{tabular}

From: ANTONY FRED
(c) (i) Using the data source created in (a) and the main document created in (b), generate customized invoice for each client.
(ii) Save the merged invoice as inwoicemerged in the KNECEXAMINDEXNO. (1/2 mari)
(d) Print out later:
(i) invoicedatasource;
(ii) invoicemerged.

TASK 2
Lentice Company intends to use a spreadshect program to manage its stock. Assume that you have been tasked to assist in the computerization.
(a) Open a spreadsheet program and type the information in sheet 1 as it appears in Figure 1. Save the workbook as stock in the KNECEXAMINDEXNO.
( 6 marks)
\begin{tabular}{|c|c|c|c|c|c|c|}
\hline & A ${ }^{\text {a }}$ & ![](https://cdn.mathpix.com/cropped/2025_04_03_2ac19fb50e031e41107bg-05.jpg?height=63\&width=207\&top_left_y=494\&top_left_x=895) & ![](https://cdn.mathpix.com/cropped/2025_04_03_2ac19fb50e031e41107bg-05.jpg?height=63\&width=165\&top_left_y=494\&top_left_x=1118) & D ${ }^{\text {a }}$ & E & F.fer \\
\hline 5. & Items & Item Category & Cost per item (Ksh) & Quantity sold & Total Price & Discount \\
\hline 2 & Mattresses & dorm001 & 3000 & 200 & & \\
\hline 3 & Blankets & dorm001 & 1500 & 300 & & \\
\hline 4 & Exercisc Books & lib001 & 150 & 2000 & & \\
\hline & Computer desk & comp001 & 7500 & 150 & & \\
\hline 16 & Text books & lib001 & 2400 & 700 & & \\
\hline 37 & Desktop computer & comp001 & 22000 & 55 & & \\
\hline W84 & Sheets & dorm001 & 1500 & 300 & & \\
\hline & Beds & derm001 & 1500 & 300 & & \\
\hline 10 & Buckets & dorm001 & 200 & 400 & & \\
\hline 51 & Printing papers & comp001 & 660 & 150 & & \\
\hline 213 & & & & & - & \\
\hline ![](https://cdn.mathpix.com/cropped/2025_04_03_2ac19fb50e031e41107bg-05.jpg?height=104\&width=87\&top_left_y=1331\&top_left_x=406) & $$\begin{aligned}
& \text { DISCOUNT } \\
& \text { RATES }
\end{aligned}$$ & & & & & \\
\hline 114 & & & - & & 2 & 3 U 20 \\
\hline 45 & dorm001 & 2\% & & & & \\
\hline 16 & lib001 & 3\% & & & & $\cdots$ \\
\hline 3 & comp001 & $4 \%$ & & & & - \\
\hline
\end{tabular}

Figure 1
(b) (i) Copy the contents of sbeet 1 to sheet 2 .
(1/2 mark)
(ii) Rename shcet 2 as stockmaintained.
(1/2 mark)
(c) Perform the tollowing in the sheet named stockmaintained.
(i) Insert a row above row I and enter the title "LENTICE COMPANY' LIMITED ITEMS SOLD" in it.
(ii) Merge the cells in the range A 1 to Fl .
(iii) Change the background color of the range A2 .F2 to grey.
(d) The company offers a discount in \% on each item based on the item eategory. Using cell references and cell addresses only:
(i) compute the total price of each item; (1 mark)
(ii) compute the discount on each item using If function.
(2 marks)
(c) Create a bar chart showing the item and the total prices. Label the chart appropriately.
(f) Print out later.
(i) Graph:
(ii) Stockmainained.

TASK 3

Lentice Company Limited also owns a Phamacy and they would like to manage information about thi pharmacy using a database. Assuming that you have been tasked to manage the stock in the pharmacy,
(a) Open a database program and create a database file named Phamacy in the KNECEXAMINDEXNO folder.
(b) Create each of the following three tables named pharmacy, drug and pharmacist in the database created in (a).

Pharmacy Details
\begin{tabular}{|l|l|l|}
\hline Field Name & Data Type & Properties \\
\hline DrugID & Text & Field size 5 \\
\hline Drugrame & Text & Field Size 15 \\
\hline Selling Price & Currency & Standard \\
\hline Quantity & Number & Long integer \\
\hline Date issued & Date & Short date \\
\hline
\end{tabular}

Pharmacist Details
\begin{tabular}{|l|l|l|}
\hline Fieid Name & Data Type & Properties \\
\hline PharmacistID & Text & Field Size 5 \\
\hline PharmacistName & Text & Field Size 15 \\
\hline
\end{tabular}

Drug Details
\begin{tabular}{|l|l|l|}
\hline Field Name & Data Type & Properties \\
\hline DruglD & Text & Field Size S \\
\hline DrugNam: & Text & Field Size 15 \\
\hline
\end{tabular}
(c) Set the fields pharmacistid and drugid as the primary keys for the tables pharmacist and drug respectively.
(1/2 mark)
(d) Create an appropriate relationship betwees the lables.
(e) Create three forms named pharmacist, pharmacy and drug to be used to enter data in the three tables created.
(f) Enter the following data in their respective tables.
\begin{tabular}{|l|l|}
\hline \multicolumn{2}{|c|}{ PHARMACIST DETAILS } \\
\hline PharmacistID & \begin{tabular}{l} 
Pharmacist \\
name
\end{tabular} \\
\hline 236 & \begin{tabular}{l} 
Miriam
\end{tabular} \\
\hline 222 & Dolly \\
\hline 214 & Peter \\
\hline 233 & Tom \\
\hline
\end{tabular}

\section*{DREGDEPAILS}
\begin{tabular}{|l|l|}
\hline \multicolumn{2}{|c|}{ DREG DEPAIIS } \\
\hline DrugID & Drugname \\
\hline Z012 & ZYCET \\
\hline V001 & VENTOLIN \\
\hline U020 & ULGEL \\
\hline P1001 & PANADOI \\
\hline
\end{tabular}
\begin{tabular}{|l|l|l|l|l|}
\hline \multicolumn{6}{|c|}{ PHARMACV DETAILS } \\
\hline DrugID & \begin{tabular}{l} 
Selling \\
Price
\end{tabular} & Date Issued & Quantity & \begin{tabular}{l} 
Pharmacist \\
ID
\end{tabular} \\
\hline$Z 012$ & 700.00 & $12 / 01 / 2014$ & 34 & 233 \\
\hline P1001 & 5.00 & $11 / 11 / 2014$ & 200 & 236 \\
\hline U020 & 800.00 & $12 / 10 / 2014$ & 78 & 222 \\
\hline$Z 012$ & 700.00 & $12 / 12 / 2014$ & 59 & 214 \\
\hline P1001 & 5.00 & $23 / 12 / 2014$ & 450 & 222 \\
\hline V001 & 250.00 & $13 / 05 / 2014$ & 70 & 233 \\
\hline
\end{tabular}
(g) Create a query named totalcostquery to display the fields; drugno, drugname, quantity, pharmarist, selling price and the total cost where total cost is quantity *selling price. Save the query as totalcostquery.
(h) Create a report for the query created in (g).
(j) Print out later:
(i) Pharmacist table, pharmacy table and drug table
(ii) Totalcostquery.

\section*{TASK 4}

Lentice Company owns a hospital and the management intends to make a presentation．Assuming you have been tasked to create slides in the presentation．
（a）Open a presentation program and create a presentation document using the details provided in Table 2．Use appropriate slide layout in each case．Save the presentation as lenticehospitalservices in the KNECEXAMINDEXNO folder，
\begin{tabular}{|c|c|c|c|c|c|}
\hline Slide No． & \multicolumn{5}{|l|}{Contents} \\
\hline \multirow[t]{2}{*}{1} & \multicolumn{5}{|l|}{} \\
\hline & \multicolumn{5}{|c|}{BY SENIOR DOCTOR} \\
\hline \multirow[t]{2}{*}{2} & \multicolumn{5}{|l|}{\multirow[t]{2}{*}{\begin{tabular}{l}
Our services \\
＊ 24 Hour Pharmacy \\
Our pharmacy is fully stocked with branded medical＇facilities with drugs available at great discounts． \\
＊Maternity services． \\
Aftordable packages available from ante－natal care，delivery and post natal care． \\
$\therefore$ X－Rays \\
The hospital is equipped to carry out different types of X－rays and affordable prices \\
Other services inctude children welfare clinics，connseliing services， ambulance，physiotherapy and laboratory
\end{tabular}}} \\
\hline & & & & & \\
\hline \multirow[t]{7}{*}{3} & \multicolumn{5}{|l|}{} \\
\hline & Day & Clinics & Time & Super Wing & General Wing \\
\hline & MONDAY & Gynaccology clinics & 8 & 5000.00 & 3000.00 \\
\hline & TUESDAY & Ante natal clinics & $$\begin{aligned}
& \infty \\
& \infty \\
& =
\end{aligned}$$ & 2500.00 & 3500.00 \\
\hline & WEDNESDAY & Orthopaedics clinics & $$\begin{aligned}
& \text { 䂞景 } \\
& 100
\end{aligned}$$ & 6000.00 & 4500.00 \\
\hline & THURSDAY & Well Baby Clinics & $$\begin{aligned}
& 4.8 \\
& 5 \\
& \hline
\end{aligned}$$ & 2000．00 & 3000.00 \\
\hline & FRIDAY & Surgical clinics & \& & 5500．00 & 4500.00 \\
\hline 4 & \multicolumn{5}{|l|}{BAR CHART} \\
\hline 5 & & & End Enk Yo & & \\
\hline
\end{tabular}

Table 2
(b) Using data in slide 3 create a bar chart as shown below in slide 4. Latol the chart appropriately.
![](https://cdn.mathpix.com/cropped/2025_04_03_2ac19fb50e031e41107bg-10.jpg?height=788&width=1311&top_left_y=358&top_left_x=291)
(c) Apply a slide transition of your choice on all the slides in the presentation
(1 mark)
(d) Save the changes to print out later as handouts with three stides per page.
(1 mark)
--- Converted MMD End ---
